/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * API REST do **MindMeet**, uma plataforma de gestão para clínicas e consultórios de psicologia.

Permite o gerenciamento completo de psicólogos, pacientes, agendamentos e anotações clínicas, com suporte a dois modelos de operação:

- **Independente** — psicólogo autônomo que gerencia sua própria agenda e pacientes.
- **Institucional** — psicólogos e estagiários vinculados a uma instituição, supervisionados por um gestor.

A autenticação é feita via **JWT**. Todos os endpoints protegidos exigem o token no header `Authorization: Bearer <token>`.
 * OpenAPI spec version: 0.1.0
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'
import { useMutation, useQuery } from '@tanstack/react-query'

import type {
  Agendamento,
  AgendamentoListParams,
  AgendaPessoalParams,
  PaginatedAgendamentoList,
  PatchedAgendamento,
} from '../../models'
import type { BodyType, ErrorType } from '../../mutator/custom-instance'
import { customInstance } from '../../mutator/custom-instance'

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
  T,
>() => T extends Y ? 1 : 2
  ? A
  : B

type WritableKeys<T> = {
  [P in keyof T]-?: IfEquals<
    { [Q in P]: T[P] },
    { -readonly [Q in P]: T[P] },
    P
  >
}[keyof T]

type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (
  k: infer I
) => void
  ? I
  : never
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never

type Writable<T> = Pick<T, WritableKeys<T>>
type NonReadonly<T> = [T] extends [UnionToIntersection<T>]
  ? {
      [P in keyof Writable<T>]: T[P] extends object
        ? NonReadonly<NonNullable<T[P]>>
        : T[P]
    }
  : DistributeReadOnlyOverUnions<T>

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Retorna uma lista com todos os agendamentos associados ao psicólogo autenticado. Pode ser filtrada pelo estado do agendamento através do parâmetro `estado`.
 * @summary Lista todos os agendamentos do psicólogo
 */
export const agendamentoList = (
  params?: AgendamentoListParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<PaginatedAgendamentoList>(
    { url: `/api/agendamentos/`, method: 'GET', params, signal },
    options
  )
}

export const getAgendamentoListQueryKey = (params?: AgendamentoListParams) => {
  return [`/api/agendamentos/`, ...(params ? [params] : [])] as const
}

export const getAgendamentoListQueryOptions = <
  TData = Awaited<ReturnType<typeof agendamentoList>>,
  TError = ErrorType<null | null>,
>(
  params?: AgendamentoListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof agendamentoList>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getAgendamentoListQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof agendamentoList>>> = ({
    signal,
  }) => agendamentoList(params, requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof agendamentoList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AgendamentoListQueryResult = NonNullable<
  Awaited<ReturnType<typeof agendamentoList>>
>
export type AgendamentoListQueryError = ErrorType<null | null>

export function useAgendamentoList<
  TData = Awaited<ReturnType<typeof agendamentoList>>,
  TError = ErrorType<null | null>,
>(
  params: undefined | AgendamentoListParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof agendamentoList>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof agendamentoList>>,
          TError,
          Awaited<ReturnType<typeof agendamentoList>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useAgendamentoList<
  TData = Awaited<ReturnType<typeof agendamentoList>>,
  TError = ErrorType<null | null>,
>(
  params?: AgendamentoListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof agendamentoList>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof agendamentoList>>,
          TError,
          Awaited<ReturnType<typeof agendamentoList>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useAgendamentoList<
  TData = Awaited<ReturnType<typeof agendamentoList>>,
  TError = ErrorType<null | null>,
>(
  params?: AgendamentoListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof agendamentoList>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Lista todos os agendamentos do psicólogo
 */

export function useAgendamentoList<
  TData = Awaited<ReturnType<typeof agendamentoList>>,
  TError = ErrorType<null | null>,
>(
  params?: AgendamentoListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof agendamentoList>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getAgendamentoListQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Permite que um **psicólogo** crie um novo agendamento, informando os dados necessários no corpo da requisição.
 * @summary Cria um novo agendamento
 */
export const agendamentoCreate = (
  agendamento: BodyType<NonReadonly<Agendamento>>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<Agendamento>(
    {
      url: `/api/agendamentos/`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: agendamento,
      signal,
    },
    options
  )
}

export const getAgendamentoCreateMutationOptions = <
  TError = ErrorType<null | null | null>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof agendamentoCreate>>,
    TError,
    { data: BodyType<NonReadonly<Agendamento>> },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof agendamentoCreate>>,
  TError,
  { data: BodyType<NonReadonly<Agendamento>> },
  TContext
> => {
  const mutationKey = ['agendamentoCreate']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof agendamentoCreate>>,
    { data: BodyType<NonReadonly<Agendamento>> }
  > = props => {
    const { data } = props ?? {}

    return agendamentoCreate(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AgendamentoCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof agendamentoCreate>>
>
export type AgendamentoCreateMutationBody = BodyType<NonReadonly<Agendamento>>
export type AgendamentoCreateMutationError = ErrorType<null | null | null>

/**
 * @summary Cria um novo agendamento
 */
export const useAgendamentoCreate = <
  TError = ErrorType<null | null | null>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof agendamentoCreate>>,
      TError,
      { data: BodyType<NonReadonly<Agendamento>> },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof agendamentoCreate>>,
  TError,
  { data: BodyType<NonReadonly<Agendamento>> },
  TContext
> => {
  const mutationOptions = getAgendamentoCreateMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Retorna todos os detalhes de um agendamento pertencente ao psicólogo autenticado.
 * @summary Detalha um agendamento específico
 */
export const agendamentoDetail = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<Agendamento>(
    { url: `/api/agendamentos/${id}/`, method: 'GET', signal },
    options
  )
}

export const getAgendamentoDetailQueryKey = (id?: string) => {
  return [`/api/agendamentos/${id}/`] as const
}

export const getAgendamentoDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof agendamentoDetail>>,
  TError = ErrorType<null | null | null>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof agendamentoDetail>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getAgendamentoDetailQueryKey(id)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof agendamentoDetail>>
  > = ({ signal }) => agendamentoDetail(id, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof agendamentoDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AgendamentoDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof agendamentoDetail>>
>
export type AgendamentoDetailQueryError = ErrorType<null | null | null>

export function useAgendamentoDetail<
  TData = Awaited<ReturnType<typeof agendamentoDetail>>,
  TError = ErrorType<null | null | null>,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof agendamentoDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof agendamentoDetail>>,
          TError,
          Awaited<ReturnType<typeof agendamentoDetail>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useAgendamentoDetail<
  TData = Awaited<ReturnType<typeof agendamentoDetail>>,
  TError = ErrorType<null | null | null>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof agendamentoDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof agendamentoDetail>>,
          TError,
          Awaited<ReturnType<typeof agendamentoDetail>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useAgendamentoDetail<
  TData = Awaited<ReturnType<typeof agendamentoDetail>>,
  TError = ErrorType<null | null | null>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof agendamentoDetail>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Detalha um agendamento específico
 */

export function useAgendamentoDetail<
  TData = Awaited<ReturnType<typeof agendamentoDetail>>,
  TError = ErrorType<null | null | null>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof agendamentoDetail>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getAgendamentoDetailQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Permite que um **psicólogo** atualize parcialmente os dados de um agendamento existente.
 * @summary Atualiza os dados de um agendamento
 */
export const agendamentoUpdate = (
  id: string,
  patchedAgendamento: BodyType<NonReadonly<PatchedAgendamento>>,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<Agendamento>(
    {
      url: `/api/agendamentos/${id}/`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: patchedAgendamento,
    },
    options
  )
}

export const getAgendamentoUpdateMutationOptions = <
  TError = ErrorType<null | null | null | null>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof agendamentoUpdate>>,
    TError,
    { id: string; data: BodyType<NonReadonly<PatchedAgendamento>> },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof agendamentoUpdate>>,
  TError,
  { id: string; data: BodyType<NonReadonly<PatchedAgendamento>> },
  TContext
> => {
  const mutationKey = ['agendamentoUpdate']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof agendamentoUpdate>>,
    { id: string; data: BodyType<NonReadonly<PatchedAgendamento>> }
  > = props => {
    const { id, data } = props ?? {}

    return agendamentoUpdate(id, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AgendamentoUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof agendamentoUpdate>>
>
export type AgendamentoUpdateMutationBody = BodyType<
  NonReadonly<PatchedAgendamento>
>
export type AgendamentoUpdateMutationError = ErrorType<
  null | null | null | null
>

/**
 * @summary Atualiza os dados de um agendamento
 */
export const useAgendamentoUpdate = <
  TError = ErrorType<null | null | null | null>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof agendamentoUpdate>>,
      TError,
      { id: string; data: BodyType<NonReadonly<PatchedAgendamento>> },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof agendamentoUpdate>>,
  TError,
  { id: string; data: BodyType<NonReadonly<PatchedAgendamento>> },
  TContext
> => {
  const mutationOptions = getAgendamentoUpdateMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Permite que um **psicólogo** exclua permanentemente um agendamento de sua lista.
 * @summary Remove um agendamento existente
 */
export const agendamentoDelete = (
  id: string,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<null>(
    { url: `/api/agendamentos/${id}/`, method: 'DELETE' },
    options
  )
}

export const getAgendamentoDeleteMutationOptions = <
  TError = ErrorType<null | null | null>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof agendamentoDelete>>,
    TError,
    { id: string },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof agendamentoDelete>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['agendamentoDelete']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof agendamentoDelete>>,
    { id: string }
  > = props => {
    const { id } = props ?? {}

    return agendamentoDelete(id, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AgendamentoDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof agendamentoDelete>>
>

export type AgendamentoDeleteMutationError = ErrorType<null | null | null>

/**
 * @summary Remove um agendamento existente
 */
export const useAgendamentoDelete = <
  TError = ErrorType<null | null | null>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof agendamentoDelete>>,
      TError,
      { id: string },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof agendamentoDelete>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getAgendamentoDeleteMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Retorna todos os agendamentos do psicólogo autenticado dentro de um período determinado. O número de dias pode ser definido através do parâmetro `dias` (padrão: 7 dias).
 * @summary Lista os agendamentos futuros do psicólogo
 */
export const agendaPessoal = (
  params?: AgendaPessoalParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<Agendamento[]>(
    { url: `/api/agendamentos/agenda/`, method: 'GET', params, signal },
    options
  )
}

export const getAgendaPessoalQueryKey = (params?: AgendaPessoalParams) => {
  return [`/api/agendamentos/agenda/`, ...(params ? [params] : [])] as const
}

export const getAgendaPessoalQueryOptions = <
  TData = Awaited<ReturnType<typeof agendaPessoal>>,
  TError = ErrorType<null | null>,
>(
  params?: AgendaPessoalParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof agendaPessoal>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getAgendaPessoalQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof agendaPessoal>>> = ({
    signal,
  }) => agendaPessoal(params, requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof agendaPessoal>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AgendaPessoalQueryResult = NonNullable<
  Awaited<ReturnType<typeof agendaPessoal>>
>
export type AgendaPessoalQueryError = ErrorType<null | null>

export function useAgendaPessoal<
  TData = Awaited<ReturnType<typeof agendaPessoal>>,
  TError = ErrorType<null | null>,
>(
  params: undefined | AgendaPessoalParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof agendaPessoal>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof agendaPessoal>>,
          TError,
          Awaited<ReturnType<typeof agendaPessoal>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useAgendaPessoal<
  TData = Awaited<ReturnType<typeof agendaPessoal>>,
  TError = ErrorType<null | null>,
>(
  params?: AgendaPessoalParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof agendaPessoal>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof agendaPessoal>>,
          TError,
          Awaited<ReturnType<typeof agendaPessoal>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useAgendaPessoal<
  TData = Awaited<ReturnType<typeof agendaPessoal>>,
  TError = ErrorType<null | null>,
>(
  params?: AgendaPessoalParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof agendaPessoal>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Lista os agendamentos futuros do psicólogo
 */

export function useAgendaPessoal<
  TData = Awaited<ReturnType<typeof agendaPessoal>>,
  TError = ErrorType<null | null>,
>(
  params?: AgendaPessoalParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof agendaPessoal>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getAgendaPessoalQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = queryOptions.queryKey

  return query
}
