/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type {
  Anotacao,
  AnotacaoListParams,
  CriarAnotacao,
  PaginatedAnotacaoList,
  PatchedAnotacao,
} from '../../models'

import { customInstance } from '../../mutator/custom-instance'
import type { ErrorType, BodyType } from '../../mutator/custom-instance'

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
  T,
>() => T extends Y ? 1 : 2
  ? A
  : B

type WritableKeys<T> = {
  [P in keyof T]-?: IfEquals<
    { [Q in P]: T[P] },
    { -readonly [Q in P]: T[P] },
    P
  >
}[keyof T]

type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (
  k: infer I
) => void
  ? I
  : never
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never

type Writable<T> = Pick<T, WritableKeys<T>>
type NonReadonly<T> = [T] extends [UnionToIntersection<T>]
  ? {
      [P in keyof Writable<T>]: T[P] extends object
        ? NonReadonly<NonNullable<T[P]>>
        : T[P]
    }
  : DistributeReadOnlyOverUnions<T>

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Retorna uma lista com todas as anotações associadas ao paciente. Também vísivel ao supervisor do psicólogo.
 * @summary Lista todas as anotações de um paciente
 */
export const anotacaoList = (
  pacientePk: string,
  params?: AnotacaoListParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<PaginatedAnotacaoList>(
    {
      url: `/api/pacientes/${pacientePk}/anotacoes/`,
      method: 'GET',
      params,
      signal,
    },
    options
  )
}

export const getAnotacaoListQueryKey = (
  pacientePk?: string,
  params?: AnotacaoListParams
) => {
  return [
    `/api/pacientes/${pacientePk}/anotacoes/`,
    ...(params ? [params] : []),
  ] as const
}

export const getAnotacaoListQueryOptions = <
  TData = Awaited<ReturnType<typeof anotacaoList>>,
  TError = ErrorType<null | null>,
>(
  pacientePk: string,
  params?: AnotacaoListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof anotacaoList>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getAnotacaoListQueryKey(pacientePk, params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof anotacaoList>>> = ({
    signal,
  }) => anotacaoList(pacientePk, params, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: !!pacientePk,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof anotacaoList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AnotacaoListQueryResult = NonNullable<
  Awaited<ReturnType<typeof anotacaoList>>
>
export type AnotacaoListQueryError = ErrorType<null | null>

export function useAnotacaoList<
  TData = Awaited<ReturnType<typeof anotacaoList>>,
  TError = ErrorType<null | null>,
>(
  pacientePk: string,
  params: undefined | AnotacaoListParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof anotacaoList>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof anotacaoList>>,
          TError,
          Awaited<ReturnType<typeof anotacaoList>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useAnotacaoList<
  TData = Awaited<ReturnType<typeof anotacaoList>>,
  TError = ErrorType<null | null>,
>(
  pacientePk: string,
  params?: AnotacaoListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof anotacaoList>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof anotacaoList>>,
          TError,
          Awaited<ReturnType<typeof anotacaoList>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useAnotacaoList<
  TData = Awaited<ReturnType<typeof anotacaoList>>,
  TError = ErrorType<null | null>,
>(
  pacientePk: string,
  params?: AnotacaoListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof anotacaoList>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Lista todas as anotações de um paciente
 */

export function useAnotacaoList<
  TData = Awaited<ReturnType<typeof anotacaoList>>,
  TError = ErrorType<null | null>,
>(
  pacientePk: string,
  params?: AnotacaoListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof anotacaoList>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getAnotacaoListQueryOptions(pacientePk, params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Recebe um JSON com os campos necessários para criar a anotação e retorna a anotação criada.
 * @summary Cria uma anotação para um paciente
 */
export const anotacaoCreate = (
  pacientePk: string,
  criarAnotacao: BodyType<NonReadonly<CriarAnotacao>>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<Anotacao>(
    {
      url: `/api/pacientes/${pacientePk}/anotacoes/`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: criarAnotacao,
      signal,
    },
    options
  )
}

export const getAnotacaoCreateMutationOptions = <
  TError = ErrorType<null | null | null>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof anotacaoCreate>>,
    TError,
    { pacientePk: string; data: BodyType<NonReadonly<CriarAnotacao>> },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof anotacaoCreate>>,
  TError,
  { pacientePk: string; data: BodyType<NonReadonly<CriarAnotacao>> },
  TContext
> => {
  const mutationKey = ['anotacaoCreate']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof anotacaoCreate>>,
    { pacientePk: string; data: BodyType<NonReadonly<CriarAnotacao>> }
  > = props => {
    const { pacientePk, data } = props ?? {}

    return anotacaoCreate(pacientePk, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AnotacaoCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof anotacaoCreate>>
>
export type AnotacaoCreateMutationBody = BodyType<NonReadonly<CriarAnotacao>>
export type AnotacaoCreateMutationError = ErrorType<null | null | null>

/**
 * @summary Cria uma anotação para um paciente
 */
export const useAnotacaoCreate = <
  TError = ErrorType<null | null | null>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof anotacaoCreate>>,
      TError,
      { pacientePk: string; data: BodyType<NonReadonly<CriarAnotacao>> },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof anotacaoCreate>>,
  TError,
  { pacientePk: string; data: BodyType<NonReadonly<CriarAnotacao>> },
  TContext
> => {
  const mutationOptions = getAnotacaoCreateMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Retorna todos os dados de uma anotação vinculada a um paciente. Também vísivel ao supervisor do psicólogo.
 * @summary Obtém detalhes sobre uma anotação
 */
export const anotacaoDetail = (
  pacientePk: string,
  id: number,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<Anotacao>(
    {
      url: `/api/pacientes/${pacientePk}/anotacoes/${id}/`,
      method: 'GET',
      signal,
    },
    options
  )
}

export const getAnotacaoDetailQueryKey = (pacientePk?: string, id?: number) => {
  return [`/api/pacientes/${pacientePk}/anotacoes/${id}/`] as const
}

export const getAnotacaoDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof anotacaoDetail>>,
  TError = ErrorType<null | null | null>,
>(
  pacientePk: string,
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof anotacaoDetail>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getAnotacaoDetailQueryKey(pacientePk, id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof anotacaoDetail>>> = ({
    signal,
  }) => anotacaoDetail(pacientePk, id, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: !!(pacientePk && id),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof anotacaoDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AnotacaoDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof anotacaoDetail>>
>
export type AnotacaoDetailQueryError = ErrorType<null | null | null>

export function useAnotacaoDetail<
  TData = Awaited<ReturnType<typeof anotacaoDetail>>,
  TError = ErrorType<null | null | null>,
>(
  pacientePk: string,
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof anotacaoDetail>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof anotacaoDetail>>,
          TError,
          Awaited<ReturnType<typeof anotacaoDetail>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useAnotacaoDetail<
  TData = Awaited<ReturnType<typeof anotacaoDetail>>,
  TError = ErrorType<null | null | null>,
>(
  pacientePk: string,
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof anotacaoDetail>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof anotacaoDetail>>,
          TError,
          Awaited<ReturnType<typeof anotacaoDetail>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useAnotacaoDetail<
  TData = Awaited<ReturnType<typeof anotacaoDetail>>,
  TError = ErrorType<null | null | null>,
>(
  pacientePk: string,
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof anotacaoDetail>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Obtém detalhes sobre uma anotação
 */

export function useAnotacaoDetail<
  TData = Awaited<ReturnType<typeof anotacaoDetail>>,
  TError = ErrorType<null | null | null>,
>(
  pacientePk: string,
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof anotacaoDetail>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getAnotacaoDetailQueryOptions(pacientePk, id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Recebe um JSON com os dados que deseja atualizar e retorna a anotação atualizada.
 * @summary Atualiza parcialmente uma anotação
 */
export const anotacaoUpdate = (
  pacientePk: string,
  id: number,
  patchedAnotacao: BodyType<NonReadonly<PatchedAnotacao>>,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<Anotacao>(
    {
      url: `/api/pacientes/${pacientePk}/anotacoes/${id}/`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: patchedAnotacao,
    },
    options
  )
}

export const getAnotacaoUpdateMutationOptions = <
  TError = ErrorType<null | null>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof anotacaoUpdate>>,
    TError,
    {
      pacientePk: string
      id: number
      data: BodyType<NonReadonly<PatchedAnotacao>>
    },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof anotacaoUpdate>>,
  TError,
  {
    pacientePk: string
    id: number
    data: BodyType<NonReadonly<PatchedAnotacao>>
  },
  TContext
> => {
  const mutationKey = ['anotacaoUpdate']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof anotacaoUpdate>>,
    {
      pacientePk: string
      id: number
      data: BodyType<NonReadonly<PatchedAnotacao>>
    }
  > = props => {
    const { pacientePk, id, data } = props ?? {}

    return anotacaoUpdate(pacientePk, id, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AnotacaoUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof anotacaoUpdate>>
>
export type AnotacaoUpdateMutationBody = BodyType<NonReadonly<PatchedAnotacao>>
export type AnotacaoUpdateMutationError = ErrorType<null | null>

/**
 * @summary Atualiza parcialmente uma anotação
 */
export const useAnotacaoUpdate = <
  TError = ErrorType<null | null>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof anotacaoUpdate>>,
      TError,
      {
        pacientePk: string
        id: number
        data: BodyType<NonReadonly<PatchedAnotacao>>
      },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof anotacaoUpdate>>,
  TError,
  {
    pacientePk: string
    id: number
    data: BodyType<NonReadonly<PatchedAnotacao>>
  },
  TContext
> => {
  const mutationOptions = getAnotacaoUpdateMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Remove permanentemente uma anotação vinculada a um paciente.
 * @summary Remove uma anotação
 */
export const anotacaoDelete = (
  pacientePk: string,
  id: number,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<null>(
    { url: `/api/pacientes/${pacientePk}/anotacoes/${id}/`, method: 'DELETE' },
    options
  )
}

export const getAnotacaoDeleteMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof anotacaoDelete>>,
    TError,
    { pacientePk: string; id: number },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof anotacaoDelete>>,
  TError,
  { pacientePk: string; id: number },
  TContext
> => {
  const mutationKey = ['anotacaoDelete']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof anotacaoDelete>>,
    { pacientePk: string; id: number }
  > = props => {
    const { pacientePk, id } = props ?? {}

    return anotacaoDelete(pacientePk, id, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AnotacaoDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof anotacaoDelete>>
>

export type AnotacaoDeleteMutationError = ErrorType<unknown>

/**
 * @summary Remove uma anotação
 */
export const useAnotacaoDelete = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof anotacaoDelete>>,
      TError,
      { pacientePk: string; id: number },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof anotacaoDelete>>,
  TError,
  { pacientePk: string; id: number },
  TContext
> => {
  const mutationOptions = getAnotacaoDeleteMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
