/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * API REST do **MindMeet**, uma plataforma de gestão para clínicas e consultórios de psicologia.

Permite o gerenciamento completo de psicólogos, pacientes, agendamentos e anotações clínicas, com suporte a dois modelos de operação:

- **Independente** — psicólogo autônomo que gerencia sua própria agenda e pacientes.
- **Institucional** — psicólogos e estagiários vinculados a uma instituição, supervisionados por um gestor.

A autenticação é feita via **JWT**. Todos os endpoints protegidos exigem o token no header `Authorization: Bearer <token>`.
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type {
  AdicionarHorarios,
  AgendaDisponivelParams,
  AgendaDisponivelResponse,
  Disponibilidade,
  PatchedDisponibilidade,
} from '../../models'

import { customInstance } from '../../mutator/custom-instance'
import type { ErrorType, BodyType } from '../../mutator/custom-instance'

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
  T,
>() => T extends Y ? 1 : 2
  ? A
  : B

type WritableKeys<T> = {
  [P in keyof T]-?: IfEquals<
    { [Q in P]: T[P] },
    { -readonly [Q in P]: T[P] },
    P
  >
}[keyof T]

type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (
  k: infer I
) => void
  ? I
  : never
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never

type Writable<T> = Pick<T, WritableKeys<T>>
type NonReadonly<T> = [T] extends [UnionToIntersection<T>]
  ? {
      [P in keyof Writable<T>]: T[P] extends object
        ? NonReadonly<NonNullable<T[P]>>
        : T[P]
    }
  : DistributeReadOnlyOverUnions<T>

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Retorna todas as disponibilidades cadastradas pelo psicólogo autenticado, incluindo os horários associados a cada dia disponível.
 * @summary Lista todas as disponibilidades do psicólogo
 */
export const disponibilidadeList = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<Disponibilidade[]>(
    { url: `/api/disponibilidades/`, method: 'GET', signal },
    options
  )
}

export const getDisponibilidadeListQueryKey = () => {
  return [`/api/disponibilidades/`] as const
}

export const getDisponibilidadeListQueryOptions = <
  TData = Awaited<ReturnType<typeof disponibilidadeList>>,
  TError = ErrorType<null>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof disponibilidadeList>>,
      TError,
      TData
    >
  >
  request?: SecondParameter<typeof customInstance>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getDisponibilidadeListQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof disponibilidadeList>>
  > = ({ signal }) => disponibilidadeList(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof disponibilidadeList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DisponibilidadeListQueryResult = NonNullable<
  Awaited<ReturnType<typeof disponibilidadeList>>
>
export type DisponibilidadeListQueryError = ErrorType<null>

export function useDisponibilidadeList<
  TData = Awaited<ReturnType<typeof disponibilidadeList>>,
  TError = ErrorType<null>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof disponibilidadeList>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof disponibilidadeList>>,
          TError,
          Awaited<ReturnType<typeof disponibilidadeList>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useDisponibilidadeList<
  TData = Awaited<ReturnType<typeof disponibilidadeList>>,
  TError = ErrorType<null>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof disponibilidadeList>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof disponibilidadeList>>,
          TError,
          Awaited<ReturnType<typeof disponibilidadeList>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useDisponibilidadeList<
  TData = Awaited<ReturnType<typeof disponibilidadeList>>,
  TError = ErrorType<null>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof disponibilidadeList>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Lista todas as disponibilidades do psicólogo
 */

export function useDisponibilidadeList<
  TData = Awaited<ReturnType<typeof disponibilidadeList>>,
  TError = ErrorType<null>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof disponibilidadeList>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getDisponibilidadeListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Cria uma disponibilidade vinculada ao psicólogo autenticado. O corpo da requisição deve conter as informações do dia e horários.
 * @summary Cria uma nova disponibilidade
 */
export const disponibilidadeCreate = (
  disponibilidade: BodyType<NonReadonly<Disponibilidade>>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<Disponibilidade>(
    {
      url: `/api/disponibilidades/`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: disponibilidade,
      signal,
    },
    options
  )
}

export const getDisponibilidadeCreateMutationOptions = <
  TError = ErrorType<null | null>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof disponibilidadeCreate>>,
    TError,
    { data: BodyType<NonReadonly<Disponibilidade>> },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof disponibilidadeCreate>>,
  TError,
  { data: BodyType<NonReadonly<Disponibilidade>> },
  TContext
> => {
  const mutationKey = ['disponibilidadeCreate']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof disponibilidadeCreate>>,
    { data: BodyType<NonReadonly<Disponibilidade>> }
  > = props => {
    const { data } = props ?? {}

    return disponibilidadeCreate(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type DisponibilidadeCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof disponibilidadeCreate>>
>
export type DisponibilidadeCreateMutationBody = BodyType<
  NonReadonly<Disponibilidade>
>
export type DisponibilidadeCreateMutationError = ErrorType<null | null>

/**
 * @summary Cria uma nova disponibilidade
 */
export const useDisponibilidadeCreate = <
  TError = ErrorType<null | null>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof disponibilidadeCreate>>,
      TError,
      { data: BodyType<NonReadonly<Disponibilidade>> },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof disponibilidadeCreate>>,
  TError,
  { data: BodyType<NonReadonly<Disponibilidade>> },
  TContext
> => {
  const mutationOptions = getDisponibilidadeCreateMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Retorna as informações completas de uma disponibilidade, incluindo todos os horários associados. Somente o psicólogo dono da disponibilidade pode visualizar.
 * @summary Obtém detalhes de uma disponibilidade específica
 */
export const disponibilidadeDetail = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<Disponibilidade>(
    { url: `/api/disponibilidades/${id}/`, method: 'GET', signal },
    options
  )
}

export const getDisponibilidadeDetailQueryKey = (id?: string) => {
  return [`/api/disponibilidades/${id}/`] as const
}

export const getDisponibilidadeDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof disponibilidadeDetail>>,
  TError = ErrorType<null | null>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof disponibilidadeDetail>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getDisponibilidadeDetailQueryKey(id)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof disponibilidadeDetail>>
  > = ({ signal }) => disponibilidadeDetail(id, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof disponibilidadeDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DisponibilidadeDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof disponibilidadeDetail>>
>
export type DisponibilidadeDetailQueryError = ErrorType<null | null>

export function useDisponibilidadeDetail<
  TData = Awaited<ReturnType<typeof disponibilidadeDetail>>,
  TError = ErrorType<null | null>,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof disponibilidadeDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof disponibilidadeDetail>>,
          TError,
          Awaited<ReturnType<typeof disponibilidadeDetail>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useDisponibilidadeDetail<
  TData = Awaited<ReturnType<typeof disponibilidadeDetail>>,
  TError = ErrorType<null | null>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof disponibilidadeDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof disponibilidadeDetail>>,
          TError,
          Awaited<ReturnType<typeof disponibilidadeDetail>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useDisponibilidadeDetail<
  TData = Awaited<ReturnType<typeof disponibilidadeDetail>>,
  TError = ErrorType<null | null>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof disponibilidadeDetail>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Obtém detalhes de uma disponibilidade específica
 */

export function useDisponibilidadeDetail<
  TData = Awaited<ReturnType<typeof disponibilidadeDetail>>,
  TError = ErrorType<null | null>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof disponibilidadeDetail>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getDisponibilidadeDetailQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Permite atualizar parcialmente os campos de uma disponibilidade já criada pelo psicólogo autenticado. É possível alterar o dia, ativar/desativar ou modificar horários.
 * @summary Atualiza uma disponibilidade existente
 */
export const disponibilidadeUpdate = (
  id: string,
  patchedDisponibilidade: BodyType<NonReadonly<PatchedDisponibilidade>>,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<Disponibilidade>(
    {
      url: `/api/disponibilidades/${id}/`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: patchedDisponibilidade,
    },
    options
  )
}

export const getDisponibilidadeUpdateMutationOptions = <
  TError = ErrorType<null | null | null>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof disponibilidadeUpdate>>,
    TError,
    { id: string; data: BodyType<NonReadonly<PatchedDisponibilidade>> },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof disponibilidadeUpdate>>,
  TError,
  { id: string; data: BodyType<NonReadonly<PatchedDisponibilidade>> },
  TContext
> => {
  const mutationKey = ['disponibilidadeUpdate']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof disponibilidadeUpdate>>,
    { id: string; data: BodyType<NonReadonly<PatchedDisponibilidade>> }
  > = props => {
    const { id, data } = props ?? {}

    return disponibilidadeUpdate(id, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type DisponibilidadeUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof disponibilidadeUpdate>>
>
export type DisponibilidadeUpdateMutationBody = BodyType<
  NonReadonly<PatchedDisponibilidade>
>
export type DisponibilidadeUpdateMutationError = ErrorType<null | null | null>

/**
 * @summary Atualiza uma disponibilidade existente
 */
export const useDisponibilidadeUpdate = <
  TError = ErrorType<null | null | null>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof disponibilidadeUpdate>>,
      TError,
      { id: string; data: BodyType<NonReadonly<PatchedDisponibilidade>> },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof disponibilidadeUpdate>>,
  TError,
  { id: string; data: BodyType<NonReadonly<PatchedDisponibilidade>> },
  TContext
> => {
  const mutationOptions = getDisponibilidadeUpdateMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Remove uma disponibilidade do psicólogo autenticado, incluindo todos os horários associados a ela. Essa ação é irreversível.
 * @summary Apaga uma disponibilidade
 */
export const disponibilidadeDelete = (
  id: string,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<null>(
    { url: `/api/disponibilidades/${id}/`, method: 'DELETE' },
    options
  )
}

export const getDisponibilidadeDeleteMutationOptions = <
  TError = ErrorType<null | null>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof disponibilidadeDelete>>,
    TError,
    { id: string },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof disponibilidadeDelete>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['disponibilidadeDelete']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof disponibilidadeDelete>>,
    { id: string }
  > = props => {
    const { id } = props ?? {}

    return disponibilidadeDelete(id, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type DisponibilidadeDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof disponibilidadeDelete>>
>

export type DisponibilidadeDeleteMutationError = ErrorType<null | null>

/**
 * @summary Apaga uma disponibilidade
 */
export const useDisponibilidadeDelete = <
  TError = ErrorType<null | null>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof disponibilidadeDelete>>,
      TError,
      { id: string },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof disponibilidadeDelete>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getDisponibilidadeDeleteMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Gera automaticamente horários em um dia específico da disponibilidade do psicólogo autenticado, com base nos campos informados (início, fim, duração e intervalo).
 * @summary Adiciona horários automaticamente
 */
export const adicionarHorarios = (
  adicionarHorarios: BodyType<AdicionarHorarios>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<null>(
    {
      url: `/api/disponibilidades/adicionar-horarios/`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: adicionarHorarios,
      signal,
    },
    options
  )
}

export const getAdicionarHorariosMutationOptions = <
  TError = ErrorType<null | null>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adicionarHorarios>>,
    TError,
    { data: BodyType<AdicionarHorarios> },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof adicionarHorarios>>,
  TError,
  { data: BodyType<AdicionarHorarios> },
  TContext
> => {
  const mutationKey = ['adicionarHorarios']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adicionarHorarios>>,
    { data: BodyType<AdicionarHorarios> }
  > = props => {
    const { data } = props ?? {}

    return adicionarHorarios(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AdicionarHorariosMutationResult = NonNullable<
  Awaited<ReturnType<typeof adicionarHorarios>>
>
export type AdicionarHorariosMutationBody = BodyType<AdicionarHorarios>
export type AdicionarHorariosMutationError = ErrorType<null | null>

/**
 * @summary Adiciona horários automaticamente
 */
export const useAdicionarHorarios = <
  TError = ErrorType<null | null>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adicionarHorarios>>,
      TError,
      { data: BodyType<AdicionarHorarios> },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof adicionarHorarios>>,
  TError,
  { data: BodyType<AdicionarHorarios> },
  TContext
> => {
  const mutationOptions = getAdicionarHorariosMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Retorna a agenda completa de um psicólogo, mostrando os horários livres e ocupados a partir da data atual. Inclui informações de cada dia ativo e seus respectivos horários.
 * @summary Lista os horários disponíveis de um psicólogo
 */
export const agendaDisponivel = (
  idPsicologo: string,
  params?: AgendaDisponivelParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<AgendaDisponivelResponse[]>(
    {
      url: `/api/disponibilidades/agenda/${idPsicologo}/`,
      method: 'GET',
      params,
      signal,
    },
    options
  )
}

export const getAgendaDisponivelQueryKey = (
  idPsicologo?: string,
  params?: AgendaDisponivelParams
) => {
  return [
    `/api/disponibilidades/agenda/${idPsicologo}/`,
    ...(params ? [params] : []),
  ] as const
}

export const getAgendaDisponivelQueryOptions = <
  TData = Awaited<ReturnType<typeof agendaDisponivel>>,
  TError = ErrorType<null>,
>(
  idPsicologo: string,
  params?: AgendaDisponivelParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof agendaDisponivel>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getAgendaDisponivelQueryKey(idPsicologo, params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof agendaDisponivel>>
  > = ({ signal }) =>
    agendaDisponivel(idPsicologo, params, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: !!idPsicologo,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof agendaDisponivel>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AgendaDisponivelQueryResult = NonNullable<
  Awaited<ReturnType<typeof agendaDisponivel>>
>
export type AgendaDisponivelQueryError = ErrorType<null>

export function useAgendaDisponivel<
  TData = Awaited<ReturnType<typeof agendaDisponivel>>,
  TError = ErrorType<null>,
>(
  idPsicologo: string,
  params: undefined | AgendaDisponivelParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof agendaDisponivel>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof agendaDisponivel>>,
          TError,
          Awaited<ReturnType<typeof agendaDisponivel>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useAgendaDisponivel<
  TData = Awaited<ReturnType<typeof agendaDisponivel>>,
  TError = ErrorType<null>,
>(
  idPsicologo: string,
  params?: AgendaDisponivelParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof agendaDisponivel>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof agendaDisponivel>>,
          TError,
          Awaited<ReturnType<typeof agendaDisponivel>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useAgendaDisponivel<
  TData = Awaited<ReturnType<typeof agendaDisponivel>>,
  TError = ErrorType<null>,
>(
  idPsicologo: string,
  params?: AgendaDisponivelParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof agendaDisponivel>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Lista os horários disponíveis de um psicólogo
 */

export function useAgendaDisponivel<
  TData = Awaited<ReturnType<typeof agendaDisponivel>>,
  TError = ErrorType<null>,
>(
  idPsicologo: string,
  params?: AgendaDisponivelParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof agendaDisponivel>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getAgendaDisponivelQueryOptions(
    idPsicologo,
    params,
    options
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = queryOptions.queryKey

  return query
}
