/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation } from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query'

import { customInstance } from '../../mutator/custom-instance'
import type { ErrorType } from '../../mutator/custom-instance'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Permite que um **gestor** remova o supervisor atualmente associado a um estagiário da sua instituição. Após a remoção, o campo `supervisor_confirmado` é definido como `False`.
 * @summary Remover supervisor de um estagiário
 */
export const removerSupervisor = (
  id: string,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<null>(
    { url: `/api/estagiarios/${id}/remover-supervisor/`, method: 'PATCH' },
    options
  )
}

export const getRemoverSupervisorMutationOptions = <
  TError = ErrorType<null | null | null | null>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof removerSupervisor>>,
    TError,
    { id: string },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof removerSupervisor>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['removerSupervisor']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof removerSupervisor>>,
    { id: string }
  > = props => {
    const { id } = props ?? {}

    return removerSupervisor(id, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type RemoverSupervisorMutationResult = NonNullable<
  Awaited<ReturnType<typeof removerSupervisor>>
>

export type RemoverSupervisorMutationError = ErrorType<
  null | null | null | null
>

/**
 * @summary Remover supervisor de um estagiário
 */
export const useRemoverSupervisor = <
  TError = ErrorType<null | null | null | null>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof removerSupervisor>>,
      TError,
      { id: string },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof removerSupervisor>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getRemoverSupervisorMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Permite que um **gestor** troque o supervisor associado a um estagiário dentro da mesma instituição. Apenas gestores da instituição do estagiário e do novo supervisor podem executar esta operação.
 * @summary Trocar supervisor de um estagiário
 */
export const trocarSupervisor = (
  id: string,
  novoSupervisor: string,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<null>(
    {
      url: `/api/estagiarios/${id}/trocar/${novoSupervisor}/`,
      method: 'PATCH',
    },
    options
  )
}

export const getTrocarSupervisorMutationOptions = <
  TError = ErrorType<null | null | null | null>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof trocarSupervisor>>,
    TError,
    { id: string; novoSupervisor: string },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof trocarSupervisor>>,
  TError,
  { id: string; novoSupervisor: string },
  TContext
> => {
  const mutationKey = ['trocarSupervisor']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof trocarSupervisor>>,
    { id: string; novoSupervisor: string }
  > = props => {
    const { id, novoSupervisor } = props ?? {}

    return trocarSupervisor(id, novoSupervisor, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type TrocarSupervisorMutationResult = NonNullable<
  Awaited<ReturnType<typeof trocarSupervisor>>
>

export type TrocarSupervisorMutationError = ErrorType<null | null | null | null>

/**
 * @summary Trocar supervisor de um estagiário
 */
export const useTrocarSupervisor = <
  TError = ErrorType<null | null | null | null>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof trocarSupervisor>>,
      TError,
      { id: string; novoSupervisor: string },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof trocarSupervisor>>,
  TError,
  { id: string; novoSupervisor: string },
  TContext
> => {
  const mutationOptions = getTrocarSupervisorMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
