/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * API REST do **MindMeet**, uma plataforma de gestão para clínicas e consultórios de psicologia.

Permite o gerenciamento completo de psicólogos, pacientes, agendamentos e anotações clínicas, com suporte a dois modelos de operação:

- **Independente** — psicólogo autônomo que gerencia sua própria agenda e pacientes.
- **Institucional** — psicólogos e estagiários vinculados a uma instituição, supervisionados por um gestor.

A autenticação é feita via **JWT**. Todos os endpoints protegidos exigem o token no header `Authorization: Bearer <token>`.
 * OpenAPI spec version: 0.1.0
 */

import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query'
import { useMutation } from '@tanstack/react-query'

import type { TrocarSupervisor } from '../../models'
import type { BodyType, ErrorType } from '../../mutator/custom-instance'
import { customInstance } from '../../mutator/custom-instance'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Permite que um **gestor** troque o supervisor associado a um estagiário dentro da mesma instituição, ou remova o vínculo enviando `novo_supervisor: null`. Apenas gestores da instituição do estagiário e do novo supervisor (quando informado) podem executar esta operação.
 * @summary Troca ou remove o supervisor de um estagiário
 */
export const trocarSupervisor = (
  id: string,
  trocarSupervisor: BodyType<TrocarSupervisor>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<null>(
    {
      url: `/api/estagiarios/${id}/trocar-supervisor/`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: trocarSupervisor,
      signal,
    },
    options
  )
}

export const getTrocarSupervisorMutationOptions = <
  TError = ErrorType<null | null | null | null | null>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof trocarSupervisor>>,
    TError,
    { id: string; data: BodyType<TrocarSupervisor> },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof trocarSupervisor>>,
  TError,
  { id: string; data: BodyType<TrocarSupervisor> },
  TContext
> => {
  const mutationKey = ['trocarSupervisor']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof trocarSupervisor>>,
    { id: string; data: BodyType<TrocarSupervisor> }
  > = props => {
    const { id, data } = props ?? {}

    return trocarSupervisor(id, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type TrocarSupervisorMutationResult = NonNullable<
  Awaited<ReturnType<typeof trocarSupervisor>>
>
export type TrocarSupervisorMutationBody = BodyType<TrocarSupervisor>
export type TrocarSupervisorMutationError = ErrorType<
  null | null | null | null | null
>

/**
 * @summary Troca ou remove o supervisor de um estagiário
 */
export const useTrocarSupervisor = <
  TError = ErrorType<null | null | null | null | null>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof trocarSupervisor>>,
      TError,
      { id: string; data: BodyType<TrocarSupervisor> },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof trocarSupervisor>>,
  TError,
  { id: string; data: BodyType<TrocarSupervisor> },
  TContext
> => {
  const mutationOptions = getTrocarSupervisorMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
