/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * API REST do **MindMeet**, uma plataforma de gestão para clínicas e consultórios de psicologia.

Permite o gerenciamento completo de psicólogos, pacientes, agendamentos e anotações clínicas, com suporte a dois modelos de operação:

- **Independente** — psicólogo autônomo que gerencia sua própria agenda e pacientes.
- **Institucional** — psicólogos e estagiários vinculados a uma instituição, supervisionados por um gestor.

A autenticação é feita via **JWT**. Todos os endpoints protegidos exigem o token no header `Authorization: Bearer <token>`.
 * OpenAPI spec version: 0.1.0
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'
import { useQuery } from '@tanstack/react-query'

import type { DashboardResponse } from '../../models'
import type { ErrorType } from '../../mutator/custom-instance'
import { customInstance } from '../../mutator/custom-instance'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * O formato da resposta varia conforme o vínculo do usuário: psicólogos independentes recebem um resumo sem dados institucionais, enquanto psicólogos de uma instituição recebem também o campo `vinculo_institucional`. Gestores recebem campos relacionados à sua instituição, como `instituicao` e `agendamentos_institucionais`.
 * @summary Retorna o dashboard do usuário autenticado
 */
export const dashboardDetail = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<DashboardResponse>(
    { url: `/api/dashboard/`, method: 'GET', signal },
    options
  )
}

export const getDashboardDetailQueryKey = () => {
  return [`/api/dashboard/`] as const
}

export const getDashboardDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof dashboardDetail>>,
  TError = ErrorType<null>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof dashboardDetail>>, TError, TData>
  >
  request?: SecondParameter<typeof customInstance>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getDashboardDetailQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof dashboardDetail>>> = ({
    signal,
  }) => dashboardDetail(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof dashboardDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DashboardDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof dashboardDetail>>
>
export type DashboardDetailQueryError = ErrorType<null>

export function useDashboardDetail<
  TData = Awaited<ReturnType<typeof dashboardDetail>>,
  TError = ErrorType<null>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof dashboardDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof dashboardDetail>>,
          TError,
          Awaited<ReturnType<typeof dashboardDetail>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useDashboardDetail<
  TData = Awaited<ReturnType<typeof dashboardDetail>>,
  TError = ErrorType<null>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof dashboardDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof dashboardDetail>>,
          TError,
          Awaited<ReturnType<typeof dashboardDetail>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useDashboardDetail<
  TData = Awaited<ReturnType<typeof dashboardDetail>>,
  TError = ErrorType<null>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof dashboardDetail>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Retorna o dashboard do usuário autenticado
 */

export function useDashboardDetail<
  TData = Awaited<ReturnType<typeof dashboardDetail>>,
  TError = ErrorType<null>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof dashboardDetail>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getDashboardDetailQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = queryOptions.queryKey

  return query
}
