/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type {
  Instituicao,
  ListarPsicologosParams,
  PatchedInstituicao,
  PsicologosPaginados,
} from '../../models'

import { customInstance } from '../../mutator/custom-instance'
import type { ErrorType, BodyType } from '../../mutator/custom-instance'

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
  T,
>() => T extends Y ? 1 : 2
  ? A
  : B

type WritableKeys<T> = {
  [P in keyof T]-?: IfEquals<
    { [Q in P]: T[P] },
    { -readonly [Q in P]: T[P] },
    P
  >
}[keyof T]

type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (
  k: infer I
) => void
  ? I
  : never
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never

type Writable<T> = Pick<T, WritableKeys<T>>
type NonReadonly<T> = [T] extends [UnionToIntersection<T>]
  ? {
      [P in keyof Writable<T>]: T[P] extends object
        ? NonReadonly<NonNullable<T[P]>>
        : T[P]
    }
  : DistributeReadOnlyOverUnions<T>

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Lista todos os detalhes da instituição que usuário da requisição é gestor
 * @summary Lista os detalhes de uma instituição
 */
export const instituicaoDetail = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<Instituicao>(
    { url: `/api/instituicoes/`, method: 'GET', signal },
    options
  )
}

export const getInstituicaoDetailQueryKey = () => {
  return [`/api/instituicoes/`] as const
}

export const getInstituicaoDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof instituicaoDetail>>,
  TError = ErrorType<null | null>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof instituicaoDetail>>,
      TError,
      TData
    >
  >
  request?: SecondParameter<typeof customInstance>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getInstituicaoDetailQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof instituicaoDetail>>
  > = ({ signal }) => instituicaoDetail(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof instituicaoDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type InstituicaoDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof instituicaoDetail>>
>
export type InstituicaoDetailQueryError = ErrorType<null | null>

export function useInstituicaoDetail<
  TData = Awaited<ReturnType<typeof instituicaoDetail>>,
  TError = ErrorType<null | null>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof instituicaoDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof instituicaoDetail>>,
          TError,
          Awaited<ReturnType<typeof instituicaoDetail>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useInstituicaoDetail<
  TData = Awaited<ReturnType<typeof instituicaoDetail>>,
  TError = ErrorType<null | null>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof instituicaoDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof instituicaoDetail>>,
          TError,
          Awaited<ReturnType<typeof instituicaoDetail>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useInstituicaoDetail<
  TData = Awaited<ReturnType<typeof instituicaoDetail>>,
  TError = ErrorType<null | null>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof instituicaoDetail>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Lista os detalhes de uma instituição
 */

export function useInstituicaoDetail<
  TData = Awaited<ReturnType<typeof instituicaoDetail>>,
  TError = ErrorType<null | null>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof instituicaoDetail>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getInstituicaoDetailQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Atualiza os detalhes da instituição em que o usuário da requisição é gestor
 * @summary Atualiza os dados de uma instituição
 */
export const instituicaoUpdate = (
  patchedInstituicao: BodyType<NonReadonly<PatchedInstituicao>>,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<Instituicao>(
    {
      url: `/api/instituicoes/`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: patchedInstituicao,
    },
    options
  )
}

export const getInstituicaoUpdateMutationOptions = <
  TError = ErrorType<null | null>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof instituicaoUpdate>>,
    TError,
    { data: BodyType<NonReadonly<PatchedInstituicao>> },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof instituicaoUpdate>>,
  TError,
  { data: BodyType<NonReadonly<PatchedInstituicao>> },
  TContext
> => {
  const mutationKey = ['instituicaoUpdate']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof instituicaoUpdate>>,
    { data: BodyType<NonReadonly<PatchedInstituicao>> }
  > = props => {
    const { data } = props ?? {}

    return instituicaoUpdate(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type InstituicaoUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof instituicaoUpdate>>
>
export type InstituicaoUpdateMutationBody = BodyType<
  NonReadonly<PatchedInstituicao>
>
export type InstituicaoUpdateMutationError = ErrorType<null | null>

/**
 * @summary Atualiza os dados de uma instituição
 */
export const useInstituicaoUpdate = <
  TError = ErrorType<null | null>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof instituicaoUpdate>>,
      TError,
      { data: BodyType<NonReadonly<PatchedInstituicao>> },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof instituicaoUpdate>>,
  TError,
  { data: BodyType<NonReadonly<PatchedInstituicao>> },
  TContext
> => {
  const mutationOptions = getInstituicaoUpdateMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Retorna uma lista paginada com todos os psicólogos vinculados à instituição do gestor autenticado. Inclui tanto supervisores quanto estagiários, ordenados alfabeticamente pelo nome.
 * @summary Listar psicólogos da instituição do gestor
 */
export const listarPsicologos = (
  params?: ListarPsicologosParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<PsicologosPaginados>(
    { url: `/api/instituicoes/psicologos/`, method: 'GET', params, signal },
    options
  )
}

export const getListarPsicologosQueryKey = (
  params?: ListarPsicologosParams
) => {
  return [`/api/instituicoes/psicologos/`, ...(params ? [params] : [])] as const
}

export const getListarPsicologosQueryOptions = <
  TData = Awaited<ReturnType<typeof listarPsicologos>>,
  TError = ErrorType<null | null | null>,
>(
  params?: ListarPsicologosParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listarPsicologos>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getListarPsicologosQueryKey(params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listarPsicologos>>
  > = ({ signal }) => listarPsicologos(params, requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listarPsicologos>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListarPsicologosQueryResult = NonNullable<
  Awaited<ReturnType<typeof listarPsicologos>>
>
export type ListarPsicologosQueryError = ErrorType<null | null | null>

export function useListarPsicologos<
  TData = Awaited<ReturnType<typeof listarPsicologos>>,
  TError = ErrorType<null | null | null>,
>(
  params: undefined | ListarPsicologosParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listarPsicologos>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listarPsicologos>>,
          TError,
          Awaited<ReturnType<typeof listarPsicologos>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useListarPsicologos<
  TData = Awaited<ReturnType<typeof listarPsicologos>>,
  TError = ErrorType<null | null | null>,
>(
  params?: ListarPsicologosParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listarPsicologos>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listarPsicologos>>,
          TError,
          Awaited<ReturnType<typeof listarPsicologos>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useListarPsicologos<
  TData = Awaited<ReturnType<typeof listarPsicologos>>,
  TError = ErrorType<null | null | null>,
>(
  params?: ListarPsicologosParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listarPsicologos>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Listar psicólogos da instituição do gestor
 */

export function useListarPsicologos<
  TData = Awaited<ReturnType<typeof listarPsicologos>>,
  TError = ErrorType<null | null | null>,
>(
  params?: ListarPsicologosParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listarPsicologos>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getListarPsicologosQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = queryOptions.queryKey

  return query
}
