/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * API REST do **MindMeet**, uma plataforma de gestão para clínicas e consultórios de psicologia.

Permite o gerenciamento completo de psicólogos, pacientes, agendamentos e anotações clínicas, com suporte a dois modelos de operação:

- **Independente** — psicólogo autônomo que gerencia sua própria agenda e pacientes.
- **Institucional** — psicólogos e estagiários vinculados a uma instituição, supervisionados por um gestor.

A autenticação é feita via **JWT**. Todos os endpoints protegidos exigem o token no header `Authorization: Bearer <token>`.
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type {
  CustomJWT,
  CustomLogin,
  CustomRegister,
  MUserParcial,
  PasswordChange,
  PasswordReset,
  PasswordResetConfirm,
  PatchedMUserParcial,
  ResendEmailVerification,
  RestAuthDetail,
  TokenRefresh,
  TokenVerify,
  VerifyEmail,
} from '../../models'

import { customInstance } from '../../mutator/custom-instance'
import type { ErrorType, BodyType } from '../../mutator/custom-instance'

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
  T,
>() => T extends Y ? 1 : 2
  ? A
  : B

type WritableKeys<T> = {
  [P in keyof T]-?: IfEquals<
    { [Q in P]: T[P] },
    { -readonly [Q in P]: T[P] },
    P
  >
}[keyof T]

type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (
  k: infer I
) => void
  ? I
  : never
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never

type Writable<T> = Pick<T, WritableKeys<T>>
type NonReadonly<T> = [T] extends [UnionToIntersection<T>]
  ? {
      [P in keyof Writable<T>]: T[P] extends object
        ? NonReadonly<NonNullable<T[P]>>
        : T[P]
    }
  : DistributeReadOnlyOverUnions<T>

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Check the credentials and return the REST Token
if the credentials are valid and authenticated.
Calls Django Auth login method to register User ID
in Django session framework

Accept the following POST parameters: username, password
Return the REST Framework Token Object's key.
 */
export const authLoginCreate = (
  customLogin: BodyType<CustomLogin>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<CustomJWT>(
    {
      url: `/api/auth/login/`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: customLogin,
      signal,
    },
    options
  )
}

export const getAuthLoginCreateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authLoginCreate>>,
    TError,
    { data: BodyType<CustomLogin> },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof authLoginCreate>>,
  TError,
  { data: BodyType<CustomLogin> },
  TContext
> => {
  const mutationKey = ['authLoginCreate']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authLoginCreate>>,
    { data: BodyType<CustomLogin> }
  > = props => {
    const { data } = props ?? {}

    return authLoginCreate(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AuthLoginCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authLoginCreate>>
>
export type AuthLoginCreateMutationBody = BodyType<CustomLogin>
export type AuthLoginCreateMutationError = ErrorType<unknown>

export const useAuthLoginCreate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authLoginCreate>>,
      TError,
      { data: BodyType<CustomLogin> },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authLoginCreate>>,
  TError,
  { data: BodyType<CustomLogin> },
  TContext
> => {
  const mutationOptions = getAuthLoginCreateMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Calls Django logout method and delete the Token object
assigned to the current User object.

Accepts/Returns nothing.
 */
export const authLogoutCreate = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<RestAuthDetail>(
    { url: `/api/auth/logout/`, method: 'POST', signal },
    options
  )
}

export const getAuthLogoutCreateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authLogoutCreate>>,
    TError,
    void,
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof authLogoutCreate>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['authLogoutCreate']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authLogoutCreate>>,
    void
  > = () => {
    return authLogoutCreate(requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AuthLogoutCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authLogoutCreate>>
>

export type AuthLogoutCreateMutationError = ErrorType<unknown>

export const useAuthLogoutCreate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authLogoutCreate>>,
      TError,
      void,
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authLogoutCreate>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getAuthLogoutCreateMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Calls Django Auth SetPasswordForm save method.

Accepts the following POST parameters: new_password1, new_password2
Returns the success/fail message.
 */
export const authPasswordChangeCreate = (
  passwordChange: BodyType<PasswordChange>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<RestAuthDetail>(
    {
      url: `/api/auth/password/change/`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: passwordChange,
      signal,
    },
    options
  )
}

export const getAuthPasswordChangeCreateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authPasswordChangeCreate>>,
    TError,
    { data: BodyType<PasswordChange> },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof authPasswordChangeCreate>>,
  TError,
  { data: BodyType<PasswordChange> },
  TContext
> => {
  const mutationKey = ['authPasswordChangeCreate']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authPasswordChangeCreate>>,
    { data: BodyType<PasswordChange> }
  > = props => {
    const { data } = props ?? {}

    return authPasswordChangeCreate(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AuthPasswordChangeCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authPasswordChangeCreate>>
>
export type AuthPasswordChangeCreateMutationBody = BodyType<PasswordChange>
export type AuthPasswordChangeCreateMutationError = ErrorType<unknown>

export const useAuthPasswordChangeCreate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authPasswordChangeCreate>>,
      TError,
      { data: BodyType<PasswordChange> },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authPasswordChangeCreate>>,
  TError,
  { data: BodyType<PasswordChange> },
  TContext
> => {
  const mutationOptions = getAuthPasswordChangeCreateMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Calls Django Auth PasswordResetForm save method.

Accepts the following POST parameters: email
Returns the success/fail message.
 */
export const authPasswordResetCreate = (
  passwordReset: BodyType<PasswordReset>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<RestAuthDetail>(
    {
      url: `/api/auth/password/reset/`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: passwordReset,
      signal,
    },
    options
  )
}

export const getAuthPasswordResetCreateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authPasswordResetCreate>>,
    TError,
    { data: BodyType<PasswordReset> },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof authPasswordResetCreate>>,
  TError,
  { data: BodyType<PasswordReset> },
  TContext
> => {
  const mutationKey = ['authPasswordResetCreate']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authPasswordResetCreate>>,
    { data: BodyType<PasswordReset> }
  > = props => {
    const { data } = props ?? {}

    return authPasswordResetCreate(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AuthPasswordResetCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authPasswordResetCreate>>
>
export type AuthPasswordResetCreateMutationBody = BodyType<PasswordReset>
export type AuthPasswordResetCreateMutationError = ErrorType<unknown>

export const useAuthPasswordResetCreate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authPasswordResetCreate>>,
      TError,
      { data: BodyType<PasswordReset> },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authPasswordResetCreate>>,
  TError,
  { data: BodyType<PasswordReset> },
  TContext
> => {
  const mutationOptions = getAuthPasswordResetCreateMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Password reset e-mail link is confirmed, therefore
this resets the user's password.

Accepts the following POST parameters: token, uid,
    new_password1, new_password2
Returns the success/fail message.
 */
export const authPasswordResetConfirmCreate = (
  passwordResetConfirm: BodyType<PasswordResetConfirm>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<RestAuthDetail>(
    {
      url: `/api/auth/password/reset/confirm/`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: passwordResetConfirm,
      signal,
    },
    options
  )
}

export const getAuthPasswordResetConfirmCreateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authPasswordResetConfirmCreate>>,
    TError,
    { data: BodyType<PasswordResetConfirm> },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof authPasswordResetConfirmCreate>>,
  TError,
  { data: BodyType<PasswordResetConfirm> },
  TContext
> => {
  const mutationKey = ['authPasswordResetConfirmCreate']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authPasswordResetConfirmCreate>>,
    { data: BodyType<PasswordResetConfirm> }
  > = props => {
    const { data } = props ?? {}

    return authPasswordResetConfirmCreate(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AuthPasswordResetConfirmCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authPasswordResetConfirmCreate>>
>
export type AuthPasswordResetConfirmCreateMutationBody =
  BodyType<PasswordResetConfirm>
export type AuthPasswordResetConfirmCreateMutationError = ErrorType<unknown>

export const useAuthPasswordResetConfirmCreate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authPasswordResetConfirmCreate>>,
      TError,
      { data: BodyType<PasswordResetConfirm> },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authPasswordResetConfirmCreate>>,
  TError,
  { data: BodyType<PasswordResetConfirm> },
  TContext
> => {
  const mutationOptions =
    getAuthPasswordResetConfirmCreateMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Registers a new user.

Accepts the following POST parameters: username, email, password1, password2.
 */
export const authRegistrationCreate = (
  customRegister: BodyType<CustomRegister>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<CustomJWT>(
    {
      url: `/api/auth/registration/`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: customRegister,
      signal,
    },
    options
  )
}

export const getAuthRegistrationCreateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authRegistrationCreate>>,
    TError,
    { data: BodyType<CustomRegister> },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof authRegistrationCreate>>,
  TError,
  { data: BodyType<CustomRegister> },
  TContext
> => {
  const mutationKey = ['authRegistrationCreate']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authRegistrationCreate>>,
    { data: BodyType<CustomRegister> }
  > = props => {
    const { data } = props ?? {}

    return authRegistrationCreate(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AuthRegistrationCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authRegistrationCreate>>
>
export type AuthRegistrationCreateMutationBody = BodyType<CustomRegister>
export type AuthRegistrationCreateMutationError = ErrorType<unknown>

export const useAuthRegistrationCreate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authRegistrationCreate>>,
      TError,
      { data: BodyType<CustomRegister> },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authRegistrationCreate>>,
  TError,
  { data: BodyType<CustomRegister> },
  TContext
> => {
  const mutationOptions = getAuthRegistrationCreateMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Resends another email to an unverified email.

Accepts the following POST parameter: email.
 */
export const authRegistrationResendEmailCreate = (
  resendEmailVerification: BodyType<ResendEmailVerification>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<RestAuthDetail>(
    {
      url: `/api/auth/registration/resend-email/`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: resendEmailVerification,
      signal,
    },
    options
  )
}

export const getAuthRegistrationResendEmailCreateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authRegistrationResendEmailCreate>>,
    TError,
    { data: BodyType<ResendEmailVerification> },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof authRegistrationResendEmailCreate>>,
  TError,
  { data: BodyType<ResendEmailVerification> },
  TContext
> => {
  const mutationKey = ['authRegistrationResendEmailCreate']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authRegistrationResendEmailCreate>>,
    { data: BodyType<ResendEmailVerification> }
  > = props => {
    const { data } = props ?? {}

    return authRegistrationResendEmailCreate(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AuthRegistrationResendEmailCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authRegistrationResendEmailCreate>>
>
export type AuthRegistrationResendEmailCreateMutationBody =
  BodyType<ResendEmailVerification>
export type AuthRegistrationResendEmailCreateMutationError = ErrorType<unknown>

export const useAuthRegistrationResendEmailCreate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authRegistrationResendEmailCreate>>,
      TError,
      { data: BodyType<ResendEmailVerification> },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authRegistrationResendEmailCreate>>,
  TError,
  { data: BodyType<ResendEmailVerification> },
  TContext
> => {
  const mutationOptions =
    getAuthRegistrationResendEmailCreateMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Verifies the email associated with the provided key.

Accepts the following POST parameter: key.
 */
export const authRegistrationVerifyEmailCreate = (
  verifyEmail: BodyType<VerifyEmail>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<RestAuthDetail>(
    {
      url: `/api/auth/registration/verify-email/`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: verifyEmail,
      signal,
    },
    options
  )
}

export const getAuthRegistrationVerifyEmailCreateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authRegistrationVerifyEmailCreate>>,
    TError,
    { data: BodyType<VerifyEmail> },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof authRegistrationVerifyEmailCreate>>,
  TError,
  { data: BodyType<VerifyEmail> },
  TContext
> => {
  const mutationKey = ['authRegistrationVerifyEmailCreate']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authRegistrationVerifyEmailCreate>>,
    { data: BodyType<VerifyEmail> }
  > = props => {
    const { data } = props ?? {}

    return authRegistrationVerifyEmailCreate(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AuthRegistrationVerifyEmailCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authRegistrationVerifyEmailCreate>>
>
export type AuthRegistrationVerifyEmailCreateMutationBody =
  BodyType<VerifyEmail>
export type AuthRegistrationVerifyEmailCreateMutationError = ErrorType<unknown>

export const useAuthRegistrationVerifyEmailCreate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authRegistrationVerifyEmailCreate>>,
      TError,
      { data: BodyType<VerifyEmail> },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authRegistrationVerifyEmailCreate>>,
  TError,
  { data: BodyType<VerifyEmail> },
  TContext
> => {
  const mutationOptions =
    getAuthRegistrationVerifyEmailCreateMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Takes a refresh type JSON web token and returns an access type JSON web
token if the refresh token is valid.
 */
export const authTokenRefreshCreate = (
  tokenRefresh: BodyType<NonReadonly<TokenRefresh>>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<TokenRefresh>(
    {
      url: `/api/auth/token/refresh/`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: tokenRefresh,
      signal,
    },
    options
  )
}

export const getAuthTokenRefreshCreateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authTokenRefreshCreate>>,
    TError,
    { data: BodyType<NonReadonly<TokenRefresh>> },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof authTokenRefreshCreate>>,
  TError,
  { data: BodyType<NonReadonly<TokenRefresh>> },
  TContext
> => {
  const mutationKey = ['authTokenRefreshCreate']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authTokenRefreshCreate>>,
    { data: BodyType<NonReadonly<TokenRefresh>> }
  > = props => {
    const { data } = props ?? {}

    return authTokenRefreshCreate(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AuthTokenRefreshCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authTokenRefreshCreate>>
>
export type AuthTokenRefreshCreateMutationBody = BodyType<
  NonReadonly<TokenRefresh>
>
export type AuthTokenRefreshCreateMutationError = ErrorType<unknown>

export const useAuthTokenRefreshCreate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authTokenRefreshCreate>>,
      TError,
      { data: BodyType<NonReadonly<TokenRefresh>> },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authTokenRefreshCreate>>,
  TError,
  { data: BodyType<NonReadonly<TokenRefresh>> },
  TContext
> => {
  const mutationOptions = getAuthTokenRefreshCreateMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Takes a token and indicates if it is valid.  This view provides no
information about a token's fitness for a particular use.
 */
export const authTokenVerifyCreate = (
  tokenVerify: BodyType<TokenVerify>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<TokenVerify>(
    {
      url: `/api/auth/token/verify/`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: tokenVerify,
      signal,
    },
    options
  )
}

export const getAuthTokenVerifyCreateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authTokenVerifyCreate>>,
    TError,
    { data: BodyType<TokenVerify> },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof authTokenVerifyCreate>>,
  TError,
  { data: BodyType<TokenVerify> },
  TContext
> => {
  const mutationKey = ['authTokenVerifyCreate']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authTokenVerifyCreate>>,
    { data: BodyType<TokenVerify> }
  > = props => {
    const { data } = props ?? {}

    return authTokenVerifyCreate(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AuthTokenVerifyCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authTokenVerifyCreate>>
>
export type AuthTokenVerifyCreateMutationBody = BodyType<TokenVerify>
export type AuthTokenVerifyCreateMutationError = ErrorType<unknown>

export const useAuthTokenVerifyCreate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authTokenVerifyCreate>>,
      TError,
      { data: BodyType<TokenVerify> },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authTokenVerifyCreate>>,
  TError,
  { data: BodyType<TokenVerify> },
  TContext
> => {
  const mutationOptions = getAuthTokenVerifyCreateMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Reads and updates UserModel fields
Accepts GET, PUT, PATCH methods.

Default accepted fields: username, first_name, last_name
Default display fields: pk, username, email, first_name, last_name
Read-only fields: pk, email

Returns UserModel fields.
 */
export const authUserRetrieve = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<MUserParcial>(
    { url: `/api/auth/user/`, method: 'GET', signal },
    options
  )
}

export const getAuthUserRetrieveQueryKey = () => {
  return [`/api/auth/user/`] as const
}

export const getAuthUserRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof authUserRetrieve>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof authUserRetrieve>>, TError, TData>
  >
  request?: SecondParameter<typeof customInstance>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getAuthUserRetrieveQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof authUserRetrieve>>
  > = ({ signal }) => authUserRetrieve(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof authUserRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthUserRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof authUserRetrieve>>
>
export type AuthUserRetrieveQueryError = ErrorType<unknown>

export function useAuthUserRetrieve<
  TData = Awaited<ReturnType<typeof authUserRetrieve>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof authUserRetrieve>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authUserRetrieve>>,
          TError,
          Awaited<ReturnType<typeof authUserRetrieve>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useAuthUserRetrieve<
  TData = Awaited<ReturnType<typeof authUserRetrieve>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof authUserRetrieve>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authUserRetrieve>>,
          TError,
          Awaited<ReturnType<typeof authUserRetrieve>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useAuthUserRetrieve<
  TData = Awaited<ReturnType<typeof authUserRetrieve>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof authUserRetrieve>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useAuthUserRetrieve<
  TData = Awaited<ReturnType<typeof authUserRetrieve>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof authUserRetrieve>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getAuthUserRetrieveQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Reads and updates UserModel fields
Accepts GET, PUT, PATCH methods.

Default accepted fields: username, first_name, last_name
Default display fields: pk, username, email, first_name, last_name
Read-only fields: pk, email

Returns UserModel fields.
 */
export const authUserUpdate = (
  mUserParcial: BodyType<NonReadonly<MUserParcial>>,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<MUserParcial>(
    {
      url: `/api/auth/user/`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: mUserParcial,
    },
    options
  )
}

export const getAuthUserUpdateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authUserUpdate>>,
    TError,
    { data: BodyType<NonReadonly<MUserParcial>> },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof authUserUpdate>>,
  TError,
  { data: BodyType<NonReadonly<MUserParcial>> },
  TContext
> => {
  const mutationKey = ['authUserUpdate']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authUserUpdate>>,
    { data: BodyType<NonReadonly<MUserParcial>> }
  > = props => {
    const { data } = props ?? {}

    return authUserUpdate(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AuthUserUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authUserUpdate>>
>
export type AuthUserUpdateMutationBody = BodyType<NonReadonly<MUserParcial>>
export type AuthUserUpdateMutationError = ErrorType<unknown>

export const useAuthUserUpdate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authUserUpdate>>,
      TError,
      { data: BodyType<NonReadonly<MUserParcial>> },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authUserUpdate>>,
  TError,
  { data: BodyType<NonReadonly<MUserParcial>> },
  TContext
> => {
  const mutationOptions = getAuthUserUpdateMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Reads and updates UserModel fields
Accepts GET, PUT, PATCH methods.

Default accepted fields: username, first_name, last_name
Default display fields: pk, username, email, first_name, last_name
Read-only fields: pk, email

Returns UserModel fields.
 */
export const authUserPartialUpdate = (
  patchedMUserParcial: BodyType<NonReadonly<PatchedMUserParcial>>,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<MUserParcial>(
    {
      url: `/api/auth/user/`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: patchedMUserParcial,
    },
    options
  )
}

export const getAuthUserPartialUpdateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authUserPartialUpdate>>,
    TError,
    { data: BodyType<NonReadonly<PatchedMUserParcial>> },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof authUserPartialUpdate>>,
  TError,
  { data: BodyType<NonReadonly<PatchedMUserParcial>> },
  TContext
> => {
  const mutationKey = ['authUserPartialUpdate']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authUserPartialUpdate>>,
    { data: BodyType<NonReadonly<PatchedMUserParcial>> }
  > = props => {
    const { data } = props ?? {}

    return authUserPartialUpdate(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AuthUserPartialUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authUserPartialUpdate>>
>
export type AuthUserPartialUpdateMutationBody = BodyType<
  NonReadonly<PatchedMUserParcial>
>
export type AuthUserPartialUpdateMutationError = ErrorType<unknown>

export const useAuthUserPartialUpdate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authUserPartialUpdate>>,
      TError,
      { data: BodyType<NonReadonly<PatchedMUserParcial>> },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authUserPartialUpdate>>,
  TError,
  { data: BodyType<NonReadonly<PatchedMUserParcial>> },
  TContext
> => {
  const mutationOptions = getAuthUserPartialUpdateMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
