/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * API REST do **MindMeet**, uma plataforma de gestão para clínicas e consultórios de psicologia.

Permite o gerenciamento completo de psicólogos, pacientes, agendamentos e anotações clínicas, com suporte a dois modelos de operação:

- **Independente** — psicólogo autônomo que gerencia sua própria agenda e pacientes.
- **Institucional** — psicólogos e estagiários vinculados a uma instituição, supervisionados por um gestor.

A autenticação é feita via **JWT**. Todos os endpoints protegidos exigem o token no header `Authorization: Bearer <token>`.
 * OpenAPI spec version: 0.1.0
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'
import { useQuery } from '@tanstack/react-query'

import type {
  Notificacao,
  NotificacaoListParams,
  NotificacoesPendentes,
  PaginatedNotificacaoList,
} from '../../models'
import type { ErrorType } from '../../mutator/custom-instance'
import { customInstance } from '../../mutator/custom-instance'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Retorna uma lista de todas as notificações do usuário
 * @summary Lista todas as notificações de um usuário
 */
export const notificacaoList = (
  params?: NotificacaoListParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<PaginatedNotificacaoList>(
    { url: `/api/notificacoes/`, method: 'GET', params, signal },
    options
  )
}

export const getNotificacaoListQueryKey = (params?: NotificacaoListParams) => {
  return [`/api/notificacoes/`, ...(params ? [params] : [])] as const
}

export const getNotificacaoListQueryOptions = <
  TData = Awaited<ReturnType<typeof notificacaoList>>,
  TError = ErrorType<null>,
>(
  params?: NotificacaoListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof notificacaoList>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getNotificacaoListQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof notificacaoList>>> = ({
    signal,
  }) => notificacaoList(params, requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof notificacaoList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type NotificacaoListQueryResult = NonNullable<
  Awaited<ReturnType<typeof notificacaoList>>
>
export type NotificacaoListQueryError = ErrorType<null>

export function useNotificacaoList<
  TData = Awaited<ReturnType<typeof notificacaoList>>,
  TError = ErrorType<null>,
>(
  params: undefined | NotificacaoListParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof notificacaoList>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof notificacaoList>>,
          TError,
          Awaited<ReturnType<typeof notificacaoList>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useNotificacaoList<
  TData = Awaited<ReturnType<typeof notificacaoList>>,
  TError = ErrorType<null>,
>(
  params?: NotificacaoListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof notificacaoList>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof notificacaoList>>,
          TError,
          Awaited<ReturnType<typeof notificacaoList>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useNotificacaoList<
  TData = Awaited<ReturnType<typeof notificacaoList>>,
  TError = ErrorType<null>,
>(
  params?: NotificacaoListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof notificacaoList>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Lista todas as notificações de um usuário
 */

export function useNotificacaoList<
  TData = Awaited<ReturnType<typeof notificacaoList>>,
  TError = ErrorType<null>,
>(
  params?: NotificacaoListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof notificacaoList>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getNotificacaoListQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Retorna as informações sobre uma notificação, também a marca como lida.
 * @summary Obtém detalhes sobre uma notificação
 */
export const notificacaoDetail = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<Notificacao>(
    { url: `/api/notificacoes/${id}/`, method: 'GET', signal },
    options
  )
}

export const getNotificacaoDetailQueryKey = (id?: string) => {
  return [`/api/notificacoes/${id}/`] as const
}

export const getNotificacaoDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof notificacaoDetail>>,
  TError = ErrorType<null | null>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof notificacaoDetail>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getNotificacaoDetailQueryKey(id)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof notificacaoDetail>>
  > = ({ signal }) => notificacaoDetail(id, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof notificacaoDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type NotificacaoDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof notificacaoDetail>>
>
export type NotificacaoDetailQueryError = ErrorType<null | null>

export function useNotificacaoDetail<
  TData = Awaited<ReturnType<typeof notificacaoDetail>>,
  TError = ErrorType<null | null>,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof notificacaoDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof notificacaoDetail>>,
          TError,
          Awaited<ReturnType<typeof notificacaoDetail>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useNotificacaoDetail<
  TData = Awaited<ReturnType<typeof notificacaoDetail>>,
  TError = ErrorType<null | null>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof notificacaoDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof notificacaoDetail>>,
          TError,
          Awaited<ReturnType<typeof notificacaoDetail>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useNotificacaoDetail<
  TData = Awaited<ReturnType<typeof notificacaoDetail>>,
  TError = ErrorType<null | null>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof notificacaoDetail>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Obtém detalhes sobre uma notificação
 */

export function useNotificacaoDetail<
  TData = Awaited<ReturnType<typeof notificacaoDetail>>,
  TError = ErrorType<null | null>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof notificacaoDetail>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getNotificacaoDetailQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Retorna o número total de notificações não lidas do usuário.
 * @summary Conta as notificações não lidas de um usuário
 */
export const notificacaoPendenteList = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<NotificacoesPendentes>(
    { url: `/api/notificacoes/pendentes/`, method: 'GET', signal },
    options
  )
}

export const getNotificacaoPendenteListQueryKey = () => {
  return [`/api/notificacoes/pendentes/`] as const
}

export const getNotificacaoPendenteListQueryOptions = <
  TData = Awaited<ReturnType<typeof notificacaoPendenteList>>,
  TError = ErrorType<null>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof notificacaoPendenteList>>,
      TError,
      TData
    >
  >
  request?: SecondParameter<typeof customInstance>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getNotificacaoPendenteListQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof notificacaoPendenteList>>
  > = ({ signal }) => notificacaoPendenteList(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof notificacaoPendenteList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type NotificacaoPendenteListQueryResult = NonNullable<
  Awaited<ReturnType<typeof notificacaoPendenteList>>
>
export type NotificacaoPendenteListQueryError = ErrorType<null>

export function useNotificacaoPendenteList<
  TData = Awaited<ReturnType<typeof notificacaoPendenteList>>,
  TError = ErrorType<null>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof notificacaoPendenteList>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof notificacaoPendenteList>>,
          TError,
          Awaited<ReturnType<typeof notificacaoPendenteList>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useNotificacaoPendenteList<
  TData = Awaited<ReturnType<typeof notificacaoPendenteList>>,
  TError = ErrorType<null>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof notificacaoPendenteList>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof notificacaoPendenteList>>,
          TError,
          Awaited<ReturnType<typeof notificacaoPendenteList>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useNotificacaoPendenteList<
  TData = Awaited<ReturnType<typeof notificacaoPendenteList>>,
  TError = ErrorType<null>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof notificacaoPendenteList>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Conta as notificações não lidas de um usuário
 */

export function useNotificacaoPendenteList<
  TData = Awaited<ReturnType<typeof notificacaoPendenteList>>,
  TError = ErrorType<null>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof notificacaoPendenteList>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getNotificacaoPendenteListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = queryOptions.queryKey

  return query
}
