/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type { Notificacao, NotificacoesPendentes } from '../../models'

import { customInstance } from '../../mutator/custom-instance'
import type { ErrorType } from '../../mutator/custom-instance'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Retorna uma lista de todas as notificações em que o usuário é o destinatário.
 * @summary Lista todas as notificações de um usuário
 */
export const notificacaoList = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<Notificacao[]>(
    { url: `/api/notificacoes/`, method: 'GET', signal },
    options
  )
}

export const getNotificacaoListQueryKey = () => {
  return [`/api/notificacoes/`] as const
}

export const getNotificacaoListQueryOptions = <
  TData = Awaited<ReturnType<typeof notificacaoList>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof notificacaoList>>, TError, TData>
  >
  request?: SecondParameter<typeof customInstance>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getNotificacaoListQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof notificacaoList>>> = ({
    signal,
  }) => notificacaoList(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof notificacaoList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type NotificacaoListQueryResult = NonNullable<
  Awaited<ReturnType<typeof notificacaoList>>
>
export type NotificacaoListQueryError = ErrorType<unknown>

export function useNotificacaoList<
  TData = Awaited<ReturnType<typeof notificacaoList>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof notificacaoList>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof notificacaoList>>,
          TError,
          Awaited<ReturnType<typeof notificacaoList>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useNotificacaoList<
  TData = Awaited<ReturnType<typeof notificacaoList>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof notificacaoList>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof notificacaoList>>,
          TError,
          Awaited<ReturnType<typeof notificacaoList>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useNotificacaoList<
  TData = Awaited<ReturnType<typeof notificacaoList>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof notificacaoList>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Lista todas as notificações de um usuário
 */

export function useNotificacaoList<
  TData = Awaited<ReturnType<typeof notificacaoList>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof notificacaoList>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getNotificacaoListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Retorna as informações sobre uma notificação, além de marcá-la como lida.
 * @summary Obtém detalhes sobre uma notificação
 */
export const notificacaoDetail = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<Notificacao>(
    { url: `/api/notificacoes/${id}/`, method: 'GET', signal },
    options
  )
}

export const getNotificacaoDetailQueryKey = (id?: string) => {
  return [`/api/notificacoes/${id}/`] as const
}

export const getNotificacaoDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof notificacaoDetail>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof notificacaoDetail>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getNotificacaoDetailQueryKey(id)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof notificacaoDetail>>
  > = ({ signal }) => notificacaoDetail(id, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof notificacaoDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type NotificacaoDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof notificacaoDetail>>
>
export type NotificacaoDetailQueryError = ErrorType<unknown>

export function useNotificacaoDetail<
  TData = Awaited<ReturnType<typeof notificacaoDetail>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof notificacaoDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof notificacaoDetail>>,
          TError,
          Awaited<ReturnType<typeof notificacaoDetail>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useNotificacaoDetail<
  TData = Awaited<ReturnType<typeof notificacaoDetail>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof notificacaoDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof notificacaoDetail>>,
          TError,
          Awaited<ReturnType<typeof notificacaoDetail>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useNotificacaoDetail<
  TData = Awaited<ReturnType<typeof notificacaoDetail>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof notificacaoDetail>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Obtém detalhes sobre uma notificação
 */

export function useNotificacaoDetail<
  TData = Awaited<ReturnType<typeof notificacaoDetail>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof notificacaoDetail>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getNotificacaoDetailQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Retorna todas as notificações não lidas do usuário logado, além do número total dessas
 * @summary Lista as notificações não lidas de um usuário
 */
export const notificacaoPendenteList = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<NotificacoesPendentes>(
    { url: `/api/notificacoes/pendentes/`, method: 'GET', signal },
    options
  )
}

export const getNotificacaoPendenteListQueryKey = () => {
  return [`/api/notificacoes/pendentes/`] as const
}

export const getNotificacaoPendenteListQueryOptions = <
  TData = Awaited<ReturnType<typeof notificacaoPendenteList>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof notificacaoPendenteList>>,
      TError,
      TData
    >
  >
  request?: SecondParameter<typeof customInstance>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getNotificacaoPendenteListQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof notificacaoPendenteList>>
  > = ({ signal }) => notificacaoPendenteList(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof notificacaoPendenteList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type NotificacaoPendenteListQueryResult = NonNullable<
  Awaited<ReturnType<typeof notificacaoPendenteList>>
>
export type NotificacaoPendenteListQueryError = ErrorType<unknown>

export function useNotificacaoPendenteList<
  TData = Awaited<ReturnType<typeof notificacaoPendenteList>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof notificacaoPendenteList>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof notificacaoPendenteList>>,
          TError,
          Awaited<ReturnType<typeof notificacaoPendenteList>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useNotificacaoPendenteList<
  TData = Awaited<ReturnType<typeof notificacaoPendenteList>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof notificacaoPendenteList>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof notificacaoPendenteList>>,
          TError,
          Awaited<ReturnType<typeof notificacaoPendenteList>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useNotificacaoPendenteList<
  TData = Awaited<ReturnType<typeof notificacaoPendenteList>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof notificacaoPendenteList>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Lista as notificações não lidas de um usuário
 */

export function useNotificacaoPendenteList<
  TData = Awaited<ReturnType<typeof notificacaoPendenteList>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof notificacaoPendenteList>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getNotificacaoPendenteListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = queryOptions.queryKey

  return query
}
