/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * API REST do **MindMeet**, uma plataforma de gestão para clínicas e consultórios de psicologia.

Permite o gerenciamento completo de psicólogos, pacientes, agendamentos e anotações clínicas, com suporte a dois modelos de operação:

- **Independente** — psicólogo autônomo que gerencia sua própria agenda e pacientes.
- **Institucional** — psicólogos e estagiários vinculados a uma instituição, supervisionados por um gestor.

A autenticação é feita via **JWT**. Todos os endpoints protegidos exigem o token no header `Authorization: Bearer <token>`.
 * OpenAPI spec version: 0.1.0
 */

/**
 * * `0` - 0
 * `1` - 1
 * `2` - 2
 * `3` - 3
 * `4` - 4
 * `5` - 5
 * `6` - 6
 */
export type AdicionarHorariosDiaEnum =
  (typeof AdicionarHorariosDiaEnum)[keyof typeof AdicionarHorariosDiaEnum]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdicionarHorariosDiaEnum = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
  NUMBER_5: 5,
  NUMBER_6: 6,
} as const
