/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `0` - 0
 * `1` - 1
 * `2` - 2
 * `3` - 3
 * `4` - 4
 * `5` - 5
 * `6` - 6
 */
export type AdicionarHorariosDiaEnum =
  (typeof AdicionarHorariosDiaEnum)[keyof typeof AdicionarHorariosDiaEnum]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdicionarHorariosDiaEnum = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
  NUMBER_5: 5,
  NUMBER_6: 6,
} as const
