/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * OpenAPI spec version: 1.0.0
 */
import type { AdicionarHorariosDiaEnum } from './adicionarHorariosDiaEnum'

export interface AdicionarHorarios {
  dia: AdicionarHorariosDiaEnum
  inicio: string
  fim: string
  duracao: string
  intervalo: string
}
