/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * OpenAPI spec version: 1.0.0
 */
import type { HorarioDisponivel } from './horarioDisponivel'

export interface AgendaDisponivelResponse {
  /** Índice do dia da semana (0 = Segunda, 6 = Domingo) */
  dia: number
  /** Nome legível do dia da semana */
  dia_semana: string
  /** Lista de horários disponíveis ou ocupados para o dia */
  horarios: HorarioDisponivel[]
}
