/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * OpenAPI spec version: 1.0.0
 */

export type AgendaPessoalParams = {
/**
 * Número de dias futuros a serem considerados na busca (padrão: 7).
 */
dias?: number;
};
