/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * API REST do **MindMeet**, uma plataforma de gestão para clínicas e consultórios de psicologia.

Permite o gerenciamento completo de psicólogos, pacientes, agendamentos e anotações clínicas, com suporte a dois modelos de operação:

- **Independente** — psicólogo autônomo que gerencia sua própria agenda e pacientes.
- **Institucional** — psicólogos e estagiários vinculados a uma instituição, supervisionados por um gestor.

A autenticação é feita via **JWT**. Todos os endpoints protegidos exigem o token no header `Authorization: Bearer <token>`.
 * OpenAPI spec version: 0.1.0
 */

/**
 * * `online` - Online
 * `presencial` - Presencial
 */
export type AgendamentoTipoEnum =
  (typeof AgendamentoTipoEnum)[keyof typeof AgendamentoTipoEnum]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AgendamentoTipoEnum = {
  online: 'online',
  presencial: 'presencial',
} as const
