/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * OpenAPI spec version: 1.0.0
 */

export interface Anamnese {
  readonly id: string;
  motivo_consulta?: string;
  expectativas?: string;
  historia_doenca_atual?: string;
  historico_familiar?: string;
  antecedente_psiquiatrico?: string;
  uso_substancias?: string;
  observacoes?: string;
}
