/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * OpenAPI spec version: 1.0.0
 */

export type AnotacaoListParams = {
  /**
   * Um número de página dentro do conjunto de resultados paginado.
   */
  pagina?: number
  /**
   * Número de resultados a serem retornados por página.
   */
  tamanho?: number
}
