/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * OpenAPI spec version: 1.0.0
 */

export interface Anotacao {
  readonly id: number;
  data?: string;
  /** @maxLength 255 */
  titulo: string;
  descricao?: string;
  /** @maxLength 255 */
  queixa_apresentada?: string;
  /** @maxLength 255 */
  queixa_identificada?: string;
  paciente: string;
}
