/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * OpenAPI spec version: 1.0.0
 */

export type BlankEnum = typeof BlankEnum[keyof typeof BlankEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BlankEnum = {
  '': '',
} as const;
