/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * API REST do **MindMeet**, uma plataforma de gestão para clínicas e consultórios de psicologia.

Permite o gerenciamento completo de psicólogos, pacientes, agendamentos e anotações clínicas, com suporte a dois modelos de operação:

- **Independente** — psicólogo autônomo que gerencia sua própria agenda e pacientes.
- **Institucional** — psicólogos e estagiários vinculados a uma instituição, supervisionados por um gestor.

A autenticação é feita via **JWT**. Todos os endpoints protegidos exigem o token no header `Authorization: Bearer <token>`.
 * OpenAPI spec version: 0.1.0
 */

export interface CadastrarPsicologo {
  /** @maxLength 254 */
  email?: string
  /**
   * Obrigatório. 150 caracteres ou menos. Letras, números e @/./+/-/_ apenas.
   * @maxLength 150
   * @pattern ^[\w.@+-]+$
   */
  username: string
  /** @maxLength 255 */
  nome_completo: string
  crp?: string
  /** @nullable */
  supervisor?: string | null
  is_estagiario?: boolean
}
