/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * OpenAPI spec version: 1.0.0
 */

import { BlankEnum } from './blankEnum'
import { ParentescoEnum } from './parentescoEnum'

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ContatoDeEmergenciaParentesco = {
  ...ParentescoEnum,
  ...BlankEnum,
} as const
