/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * OpenAPI spec version: 1.0.0
 */

export interface ContatoDeEmergencia {
  readonly id: string
  /** @maxLength 50 */
  nome: string
  /** @maxLength 15 */
  numero_telefone: string
  /** @maxLength 20 */
  parentesco?: string
}
