/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * OpenAPI spec version: 1.0.0
 */

export interface CriarAnotacao {
  readonly id: number;
  readonly psicologo: string;
  readonly paciente: string;
  data?: string;
  /** @maxLength 255 */
  titulo: string;
  registros?: string;
  /** @maxLength 255 */
  queixa_apresentada?: string;
  /** @maxLength 255 */
  queixa_identificada?: string;
}
