/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * OpenAPI spec version: 1.0.0
 */

export interface CriarMUser {
  /** @maxLength 255 */
  nome_completo: string
  /**
   * Obrigatório. 150 caracteres ou menos. Letras, números e @/./+/-/_ apenas.
   * @maxLength 150
   * @pattern ^[\w.@+-]+$
   */
  username: string
  /** @maxLength 254 */
  email?: string
  password: string
  /** @nullable */
  data_nascimento?: string | null
  /** @maxLength 10 */
  crp?: string
  is_estagiario?: boolean
  supervisor?: string
}
