/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * OpenAPI spec version: 1.0.0
 */

export interface CustomLogin {
  username?: string;
  email?: string;
  password: string;
}
