/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * OpenAPI spec version: 1.0.0
 */

export interface CustomRegister {
  email?: string;
  password1: string;
  password2: string;
}
