/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * OpenAPI spec version: 1.0.0
 */
import type { MUserParcial } from './mUserParcial'

/**
 * Serializer for JWT authentication.
 */
export interface CustomJWT {
  readonly access: string
  refresh: string
  readonly user: MUserParcial
}
