/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * API REST do **MindMeet**, uma plataforma de gestão para clínicas e consultórios de psicologia.

Permite o gerenciamento completo de psicólogos, pacientes, agendamentos e anotações clínicas, com suporte a dois modelos de operação:

- **Independente** — psicólogo autônomo que gerencia sua própria agenda e pacientes.
- **Institucional** — psicólogos e estagiários vinculados a uma instituição, supervisionados por um gestor.

A autenticação é feita via **JWT**. Todos os endpoints protegidos exigem o token no header `Authorization: Bearer <token>`.
 * OpenAPI spec version: 0.1.0
 */
import type { Agenda } from './agenda'
import type { AgendamentosPorEstado } from './agendamentosPorEstado'
import type { PacientesResumo } from './pacientesResumo'

export interface DashboardPsicologoIndependente {
  readonly tipo_dashboard: string
  agenda: Agenda
  agendamentos_por_estado: AgendamentosPorEstado
  taxa_realizacao: number
  pacientes: PacientesResumo
  notificacoes_nao_lidas: number
}
