/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * OpenAPI spec version: 1.0.0
 */
import type { DisponibilidadeDiaEnum } from './disponibilidadeDiaEnum';
import type { Horario } from './horario';

export interface Disponibilidade {
  readonly id: string;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   */
  dia: DisponibilidadeDiaEnum;
  readonly dia_semana: string;
  ativo?: boolean;
  horarios?: Horario[];
}
