/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `0` - Segunda-feira
* `1` - Terça-feira
* `2` - Quarta-feira
* `3` - Quinta-feira
* `4` - Sexta-feira
* `5` - Sábado
* `6` - Domingo
 */
export type DisponibilidadeDiaEnum = typeof DisponibilidadeDiaEnum[keyof typeof DisponibilidadeDiaEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DisponibilidadeDiaEnum = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
  NUMBER_5: 5,
  NUMBER_6: 6,
} as const;
