/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * OpenAPI spec version: 1.0.0
 */

export interface Endereco {
  readonly id: string
  /** @maxLength 9 */
  cep?: string
  /** @maxLength 255 */
  rua?: string
  /** @maxLength 10 */
  numero?: string
  /** @maxLength 100 */
  complemento?: string
  /** @maxLength 100 */
  bairro?: string
  /** @maxLength 100 */
  cidade?: string
  /** @maxLength 2 */
  uf?: string
}
