/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `ESCOLAR` - Psicologia Escolar/Educacional
* `ORGANIZACIONAL` - Psicologia Organizacional e do Trabalho
* `TRANSITO` - Psicologia de Trânsito
* `JURIDICA` - Psicologia Jurídica
* `ESPORTE` - Psicologia do Esporte
* `CLINICA` - Psicologia Clínica
* `HOSPITALAR` - Psicologia Hospitalar
* `PSICOPEDAGOGIA` - Psicopedagogia
* `PSICOMOTRICIDADE` - Psicomotricidade
* `SOCIAL` - Psicologia Social
* `NEURO` - Neuropsicologia
* `SAUDE` - Psicologia em Saúde
* `AVALIACAO` - Avaliação Psicológica
 */
export type EspecialidadeEnum = typeof EspecialidadeEnum[keyof typeof EspecialidadeEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EspecialidadeEnum = {
  ESCOLAR: 'ESCOLAR',
  ORGANIZACIONAL: 'ORGANIZACIONAL',
  TRANSITO: 'TRANSITO',
  JURIDICA: 'JURIDICA',
  ESPORTE: 'ESPORTE',
  CLINICA: 'CLINICA',
  HOSPITALAR: 'HOSPITALAR',
  PSICOPEDAGOGIA: 'PSICOPEDAGOGIA',
  PSICOMOTRICIDADE: 'PSICOMOTRICIDADE',
  SOCIAL: 'SOCIAL',
  NEURO: 'NEURO',
  SAUDE: 'SAUDE',
  AVALIACAO: 'AVALIACAO',
} as const;
