/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `agendado` - Agendado
* `cancelado` - Cancelado
* `realizado` - Realizado
 */
export type EstadoEnum = typeof EstadoEnum[keyof typeof EstadoEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EstadoEnum = {
  agendado: 'agendado',
  cancelado: 'cancelado',
  realizado: 'realizado',
} as const;
