/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `S` - Solteiro(a)
* `C` - Casado(a)
* `D` - Divorciado(a)
* `V` - Viúvo(a)
* `UE` - União Estável
 */
export type EstadoCivilEnum = typeof EstadoCivilEnum[keyof typeof EstadoCivilEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EstadoCivilEnum = {
  S: 'S',
  C: 'C',
  D: 'D',
  V: 'V',
  UE: 'UE',
} as const;
