/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * OpenAPI spec version: 1.0.0
 */

export interface Informacoes {
  readonly id: string;
  queixa_principal?: string;
  historico_psiquiatrico?: string;
  medicamentos_atuais?: string;
  alergias?: string;
}
