/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * OpenAPI spec version: 1.0.0
 */
import type { Endereco } from './endereco'
import type { MUser } from './mUser'

export interface Instituicao {
  readonly id: string
  /** @maxLength 255 */
  nome: string
  /**
   * @minLength 14
   * @maxLength 18
   */
  cnpj: string
  endereco?: Endereco
  gestor?: MUser
}
