/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * OpenAPI spec version: 1.0.0
 */
import type { MUser } from './mUser';

/**
 * Serializer for JWT authentication.
 */
export interface Jwt {
  access: string;
  refresh: string;
  user: MUser;
}
