/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * OpenAPI spec version: 1.0.0
 */

export type ListarPsicologosParams = {
  /**
   * Número da página a ser retornada.
   */
  pagina?: number
  /**
   * Quantidade de itens por página. Máximo de 50.
   */
  tamanho?: number
}
