/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * OpenAPI spec version: 1.0.0
 */
import type { TipoBaeEnum } from './tipoBaeEnum'

export interface MarcarAgendamento {
  psicologo: string
  data: string
  tipo: TipoBaeEnum
  horario_inicio: string
  horario_fim: string
  /** @maxLength 255 */
  paciente_nome: string
  /** @maxLength 254 */
  paciente_email: string
  /** @maxLength 15 */
  paciente_numero_telefone?: string
}
