/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * OpenAPI spec version: 1.0.0
 */
import type { MUserSexo } from './mUserSexo'
import type { Endereco } from './endereco'
import type { PapelEnum } from './papelEnum'

export interface MUser {
  readonly id: string
  /** @maxLength 255 */
  nome_completo: string
  /** @maxLength 254 */
  email?: string
  /** @maxLength 14 */
  cpf?: string
  /** @nullable */
  data_nascimento?: string | null
  /** @maxLength 15 */
  numero_telefone?: string
  sexo?: (typeof MUserSexo)[keyof typeof MUserSexo]
  readonly verificado: boolean
  endereco?: Endereco
  readonly papel: PapelEnum
  readonly vinculo: string
}
