/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * OpenAPI spec version: 1.0.0
 */
import type { MUserSexo } from './mUserSexo';
import type { Endereco } from './endereco';
import type { MUserEspecialidade } from './mUserEspecialidade';

export interface MUser {
  readonly id: string;
  /** @maxLength 255 */
  nome_completo: string;
  /** @maxLength 254 */
  email?: string;
  /** @maxLength 11 */
  cpf?: string;
  /** @nullable */
  data_nascimento?: string | null;
  /** @maxLength 15 */
  numero_telefone?: string;
  sexo?: typeof MUserSexo[keyof typeof MUserSexo] ;
  /** @maxLength 10 */
  crp?: string;
  readonly verificado: boolean;
  endereco: Endereco;
  is_estagiario?: boolean;
  /** @nullable */
  supervisor?: string | null;
  supervisor_confirmado?: boolean;
  /** @nullable */
  avatar?: string | null;
  bio?: string;
  especialidade?: typeof MUserEspecialidade[keyof typeof MUserEspecialidade] ;
  avatar_base64?: string;
}
