/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `CONFIRMACAO` - confirmação
 * `OUTRO` - outro
 */
export type NotificacaoTipoEnum =
  (typeof NotificacaoTipoEnum)[keyof typeof NotificacaoTipoEnum]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NotificacaoTipoEnum = {
  CONFIRMACAO: 'CONFIRMACAO',
  OUTRO: 'OUTRO',
} as const
