/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * OpenAPI spec version: 1.0.0
 */
import type { Notificacao } from './notificacao';

export interface NotificacoesPendentes {
  nao_lidas: number;
  notificacoes: Notificacao[];
}
