/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * API REST do **MindMeet**, uma plataforma de gestão para clínicas e consultórios de psicologia.

Permite o gerenciamento completo de psicólogos, pacientes, agendamentos e anotações clínicas, com suporte a dois modelos de operação:

- **Independente** — psicólogo autônomo que gerencia sua própria agenda e pacientes.
- **Institucional** — psicólogos e estagiários vinculados a uma instituição, supervisionados por um gestor.

A autenticação é feita via **JWT**. Todos os endpoints protegidos exigem o token no header `Authorization: Bearer <token>`.
 * OpenAPI spec version: 0.1.0
 */
import type { NotificacaoTipoEnum } from './notificacaoTipoEnum'
import type { NotificacaoDadosExtras } from './notificacaoDadosExtras'

export interface Notificacao {
  readonly id: string
  /** @maxLength 255 */
  titulo: string
  mensagem: string
  lida?: boolean
  data_criacao?: string
  tipo?: NotificacaoTipoEnum
  /** @nullable */
  dados_extras?: NotificacaoDadosExtras
}
