/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * API REST do **MindMeet**, uma plataforma de gestão para clínicas e consultórios de psicologia.

Permite o gerenciamento completo de psicólogos, pacientes, agendamentos e anotações clínicas, com suporte a dois modelos de operação:

- **Independente** — psicólogo autônomo que gerencia sua própria agenda e pacientes.
- **Institucional** — psicólogos e estagiários vinculados a uma instituição, supervisionados por um gestor.

A autenticação é feita via **JWT**. Todos os endpoints protegidos exigem o token no header `Authorization: Bearer <token>`.
 * OpenAPI spec version: 0.1.0
 */

export type PacienteListParams = {
  /**
   * Um número de página dentro do conjunto de resultados paginado.
   */
  pagina?: number
  /**
   * Buscar por todos os pacientes que contenham essa string no email ou nome.
   */
  search?: string
  /**
   * Número de resultados a serem retornados por página.
   */
  tamanho?: number
}
