/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * API REST do **MindMeet**, uma plataforma de gestão para clínicas e consultórios de psicologia.

Permite o gerenciamento completo de psicólogos, pacientes, agendamentos e anotações clínicas, com suporte a dois modelos de operação:

- **Independente** — psicólogo autônomo que gerencia sua própria agenda e pacientes.
- **Institucional** — psicólogos e estagiários vinculados a uma instituição, supervisionados por um gestor.

A autenticação é feita via **JWT**. Todos os endpoints protegidos exigem o token no header `Authorization: Bearer <token>`.
 * OpenAPI spec version: 0.1.0
 */
import type { PacienteDetailAnamnese } from './pacienteDetailAnamnese'
import type { PacienteDetailContatoEmergencia } from './pacienteDetailContatoEmergencia'
import type { PacienteDetailEndereco } from './pacienteDetailEndereco'
import type { PacienteDetailInformacoesClinicas } from './pacienteDetailInformacoesClinicas'

export interface PacienteDetail {
  readonly id: string
  /** @nullable */
  readonly acompanhado_por: string | null
  readonly psicologo: string
  /** @nullable */
  anamnese?: PacienteDetailAnamnese
  /** @nullable */
  contato_emergencia?: PacienteDetailContatoEmergencia
  /** @nullable */
  endereco?: PacienteDetailEndereco
  /** @nullable */
  informacoes_clinicas?: PacienteDetailInformacoesClinicas
  /** @maxLength 255 */
  nome_completo: string
  data_nascimento: string
  /** @maxLength 255 */
  email: string
  /** @maxLength 30 */
  numero_telefone: string
  /** @maxLength 30 */
  numero_celular?: string
  /** @maxLength 14 */
  cpf: string
  /** @maxLength 12 */
  rg?: string
  /** @maxLength 20 */
  estado_civil?: string
  /** @maxLength 255 */
  profissao?: string
}
