/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * OpenAPI spec version: 1.0.0
 */

import { BlankEnum } from './blankEnum'
import { EstadoCivilEnum } from './estadoCivilEnum'

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PacienteEstadoCivil = { ...EstadoCivilEnum, ...BlankEnum } as const
