/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * OpenAPI spec version: 1.0.0
 */
import type { Informacoes } from './informacoes';

/**
 * @nullable
 */
export type PacienteInformacoesClinicas = Informacoes | null;
