/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `ADMIN` - admin
* `PSICOLOGO` - psicologo
* `PACIENTE` - paciente
* `GESTOR` - gestor
 */
export type PapelEnum = typeof PapelEnum[keyof typeof PapelEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PapelEnum = {
  ADMIN: 'ADMIN',
  PSICOLOGO: 'PSICOLOGO',
  PACIENTE: 'PACIENTE',
  GESTOR: 'GESTOR',
} as const;
