/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `P` - Pai
 * `M` - Mãe
 * `C` - Cônjuge
 * `F` - Filho(a)
 * `I` - Irmão(ã)
 * `A` - Amigo(a)
 * `O` - Outro
 */
export type ParentescoEnum =
  (typeof ParentescoEnum)[keyof typeof ParentescoEnum]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ParentescoEnum = {
  P: 'P',
  M: 'M',
  C: 'C',
  F: 'F',
  I: 'I',
  A: 'A',
  O: 'O',
} as const
