/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Serializer for requesting a password reset e-mail.
 */
export interface PasswordReset {
  email: string
}
