/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * OpenAPI spec version: 1.0.0
 */
import type { PapelEnum } from './papelEnum';

export interface PatchedMUserParcial {
  readonly id?: string;
  readonly nome_completo?: string;
  readonly email?: string;
  readonly papel?: PapelEnum;
}
