/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * API REST do **MindMeet**, uma plataforma de gestão para clínicas e consultórios de psicologia.

Permite o gerenciamento completo de psicólogos, pacientes, agendamentos e anotações clínicas, com suporte a dois modelos de operação:

- **Independente** — psicólogo autônomo que gerencia sua própria agenda e pacientes.
- **Institucional** — psicólogos e estagiários vinculados a uma instituição, supervisionados por um gestor.

A autenticação é feita via **JWT**. Todos os endpoints protegidos exigem o token no header `Authorization: Bearer <token>`.
 * OpenAPI spec version: 0.1.0
 */

import type { Endereco } from './endereco'
import type { PapelEnum } from './papelEnum'
import type { PatchedMUserSexo } from './patchedMUserSexo'

export interface PatchedMUser {
  readonly id?: string
  /** @maxLength 255 */
  nome_completo?: string
  /** @maxLength 254 */
  email?: string
  /** @maxLength 14 */
  cpf?: string
  /** @nullable */
  data_nascimento?: string | null
  /** @maxLength 15 */
  numero_telefone?: string
  sexo?: (typeof PatchedMUserSexo)[keyof typeof PatchedMUserSexo]
  readonly verificado?: boolean
  endereco?: Endereco
  readonly papel?: PapelEnum
  readonly vinculo?: string
}
