/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * API REST do **MindMeet**, uma plataforma de gestão para clínicas e consultórios de psicologia.

Permite o gerenciamento completo de psicólogos, pacientes, agendamentos e anotações clínicas, com suporte a dois modelos de operação:

- **Independente** — psicólogo autônomo que gerencia sua própria agenda e pacientes.
- **Institucional** — psicólogos e estagiários vinculados a uma instituição, supervisionados por um gestor.

A autenticação é feita via **JWT**. Todos os endpoints protegidos exigem o token no header `Authorization: Bearer <token>`.
 * OpenAPI spec version: 0.1.0
 */
import type { PatchedPacienteDetailAnamnese } from './patchedPacienteDetailAnamnese'
import type { PatchedPacienteDetailContatoEmergencia } from './patchedPacienteDetailContatoEmergencia'
import type { PatchedPacienteDetailEndereco } from './patchedPacienteDetailEndereco'
import type { PatchedPacienteDetailInformacoesClinicas } from './patchedPacienteDetailInformacoesClinicas'

export interface PatchedPacienteDetail {
  readonly id?: string
  /** @nullable */
  readonly acompanhado_por?: string | null
  readonly psicologo?: string
  /** @nullable */
  anamnese?: PatchedPacienteDetailAnamnese
  /** @nullable */
  contato_emergencia?: PatchedPacienteDetailContatoEmergencia
  /** @nullable */
  endereco?: PatchedPacienteDetailEndereco
  /** @nullable */
  informacoes_clinicas?: PatchedPacienteDetailInformacoesClinicas
  /** @maxLength 255 */
  nome_completo?: string
  data_nascimento?: string
  /** @maxLength 255 */
  email?: string
  /** @maxLength 30 */
  numero_telefone?: string
  /** @maxLength 30 */
  numero_celular?: string
  /** @maxLength 14 */
  cpf?: string
  /** @maxLength 12 */
  rg?: string
  /** @maxLength 20 */
  estado_civil?: string
  /** @maxLength 255 */
  profissao?: string
}
