/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * OpenAPI spec version: 1.0.0
 */
import type { PatchedPacienteAnamnese } from './patchedPacienteAnamnese';
import type { PatchedPacienteContatoEmergencia } from './patchedPacienteContatoEmergencia';
import type { PatchedPacienteEndereco } from './patchedPacienteEndereco';
import type { PatchedPacienteInformacoesClinicas } from './patchedPacienteInformacoesClinicas';

export interface PatchedPaciente {
  readonly id?: string;
  /** @nullable */
  anamnese?: PatchedPacienteAnamnese;
  /** @nullable */
  contato_emergencia?: PatchedPacienteContatoEmergencia;
  /** @nullable */
  endereco?: PatchedPacienteEndereco;
  /** @nullable */
  informacoes_clinicas?: PatchedPacienteInformacoesClinicas;
  readonly acompanhado_por?: string;
  /** @maxLength 255 */
  nome_completo?: string;
  data_nascimento?: string;
  /** @maxLength 255 */
  email?: string;
  /** @maxLength 15 */
  numero_telefone?: string;
  /** @maxLength 15 */
  numero_celular?: string;
  /** @maxLength 14 */
  cpf?: string;
  /** @maxLength 12 */
  rg?: string;
  /** @maxLength 20 */
  estado_civil?: string;
  /** @maxLength 255 */
  profissao?: string;
}
