/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * OpenAPI spec version: 1.0.0
 */
import type { MUser } from './mUser'

export interface PerfilPsicologo {
  usuario?: MUser
  readonly id: string
  /**
   * @maxLength 10
   * @nullable
   */
  crp?: string | null
  is_estagiario?: boolean
  supervisor?: string
  readonly supervisor_confirmado: boolean
}
