/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * OpenAPI spec version: 1.0.0
 */
import type { PerfilPsicologo } from './perfilPsicologo'

export interface PsicologosPaginados {
  /** Total de psicólogos na instituição. */
  count: number
  /**
   * URL da próxima página, ou null se for a última.
   * @nullable
   */
  next: string | null
  /**
   * URL da página anterior, ou null se for a primeira.
   * @nullable
   */
  previous: string | null
  results: PerfilPsicologo[]
}
