/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `M` - Masculino
 * `F` - Feminino
 * `O` - Outro
 */
export type SexoEnum = (typeof SexoEnum)[keyof typeof SexoEnum]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SexoEnum = {
  M: 'M',
  F: 'F',
  O: 'O',
} as const
