/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `CONFIRMACAO` - confirmação
* `OUTRO` - outro
 */
export type TipoEnum = typeof TipoEnum[keyof typeof TipoEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TipoEnum = {
  CONFIRMACAO: 'CONFIRMACAO',
  OUTRO: 'OUTRO',
} as const;
