/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * OpenAPI spec version: 1.0.0
 */

/**
 * User model w/o password
 */
export interface UserDetails {
  readonly pk: string
  readonly email: string
  readonly first_name: string
  readonly last_name: string
}
