/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * API REST do **MindMeet**, uma plataforma de gestão para clínicas e consultórios de psicologia.

Permite o gerenciamento completo de psicólogos, pacientes, agendamentos e anotações clínicas, com suporte a dois modelos de operação:

- **Independente** — psicólogo autônomo que gerencia sua própria agenda e pacientes.
- **Institucional** — psicólogos e estagiários vinculados a uma instituição, supervisionados por um gestor.

A autenticação é feita via **JWT**. Todos os endpoints protegidos exigem o token no header `Authorization: Bearer <token>`.
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type {
  CadastrarPsicologo,
  CustomRegister,
  MUser,
  PatchedMUser,
  PatchedPerfilPsicologo,
  PerfilPsicologo,
} from '../../models'

import { customInstance } from '../../mutator/custom-instance'
import type { ErrorType, BodyType } from '../../mutator/custom-instance'

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
  T,
>() => T extends Y ? 1 : 2
  ? A
  : B

type WritableKeys<T> = {
  [P in keyof T]-?: IfEquals<
    { [Q in P]: T[P] },
    { -readonly [Q in P]: T[P] },
    P
  >
}[keyof T]

type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (
  k: infer I
) => void
  ? I
  : never
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never

type Writable<T> = Pick<T, WritableKeys<T>>
type NonReadonly<T> = [T] extends [UnionToIntersection<T>]
  ? {
      [P in keyof Writable<T>]: T[P] extends object
        ? NonReadonly<NonNullable<T[P]>>
        : T[P]
    }
  : DistributeReadOnlyOverUnions<T>

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Retorna os dados do usuário autenticado
 */
export const usuarioDetail = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<MUser>(
    { url: `/api/me/`, method: 'GET', signal },
    options
  )
}

export const getUsuarioDetailQueryKey = () => {
  return [`/api/me/`] as const
}

export const getUsuarioDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof usuarioDetail>>,
  TError = ErrorType<null>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof usuarioDetail>>, TError, TData>
  >
  request?: SecondParameter<typeof customInstance>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getUsuarioDetailQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof usuarioDetail>>> = ({
    signal,
  }) => usuarioDetail(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof usuarioDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UsuarioDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof usuarioDetail>>
>
export type UsuarioDetailQueryError = ErrorType<null>

export function useUsuarioDetail<
  TData = Awaited<ReturnType<typeof usuarioDetail>>,
  TError = ErrorType<null>,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof usuarioDetail>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usuarioDetail>>,
          TError,
          Awaited<ReturnType<typeof usuarioDetail>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useUsuarioDetail<
  TData = Awaited<ReturnType<typeof usuarioDetail>>,
  TError = ErrorType<null>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof usuarioDetail>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usuarioDetail>>,
          TError,
          Awaited<ReturnType<typeof usuarioDetail>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useUsuarioDetail<
  TData = Awaited<ReturnType<typeof usuarioDetail>>,
  TError = ErrorType<null>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof usuarioDetail>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Retorna os dados do usuário autenticado
 */

export function useUsuarioDetail<
  TData = Awaited<ReturnType<typeof usuarioDetail>>,
  TError = ErrorType<null>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof usuarioDetail>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getUsuarioDetailQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * @summary Atualiza os dados do usuário autenticado
 */
export const usuarioUpdate = (
  patchedMUser: BodyType<NonReadonly<PatchedMUser>>,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<MUser>(
    {
      url: `/api/me/`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: patchedMUser,
    },
    options
  )
}

export const getUsuarioUpdateMutationOptions = <
  TError = ErrorType<null | null>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usuarioUpdate>>,
    TError,
    { data: BodyType<NonReadonly<PatchedMUser>> },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof usuarioUpdate>>,
  TError,
  { data: BodyType<NonReadonly<PatchedMUser>> },
  TContext
> => {
  const mutationKey = ['usuarioUpdate']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof usuarioUpdate>>,
    { data: BodyType<NonReadonly<PatchedMUser>> }
  > = props => {
    const { data } = props ?? {}

    return usuarioUpdate(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UsuarioUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof usuarioUpdate>>
>
export type UsuarioUpdateMutationBody = BodyType<NonReadonly<PatchedMUser>>
export type UsuarioUpdateMutationError = ErrorType<null | null>

/**
 * @summary Atualiza os dados do usuário autenticado
 */
export const useUsuarioUpdate = <
  TError = ErrorType<null | null>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof usuarioUpdate>>,
      TError,
      { data: BodyType<NonReadonly<PatchedMUser>> },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof usuarioUpdate>>,
  TError,
  { data: BodyType<NonReadonly<PatchedMUser>> },
  TContext
> => {
  const mutationOptions = getUsuarioUpdateMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * @summary Retorna o perfil profissional do psicólogo autenticado
 */
export const perfilPsicologoDetail = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<PerfilPsicologo>(
    { url: `/api/me/perfil/`, method: 'GET', signal },
    options
  )
}

export const getPerfilPsicologoDetailQueryKey = () => {
  return [`/api/me/perfil/`] as const
}

export const getPerfilPsicologoDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof perfilPsicologoDetail>>,
  TError = ErrorType<null | null>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof perfilPsicologoDetail>>,
      TError,
      TData
    >
  >
  request?: SecondParameter<typeof customInstance>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getPerfilPsicologoDetailQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof perfilPsicologoDetail>>
  > = ({ signal }) => perfilPsicologoDetail(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof perfilPsicologoDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PerfilPsicologoDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof perfilPsicologoDetail>>
>
export type PerfilPsicologoDetailQueryError = ErrorType<null | null>

export function usePerfilPsicologoDetail<
  TData = Awaited<ReturnType<typeof perfilPsicologoDetail>>,
  TError = ErrorType<null | null>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof perfilPsicologoDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof perfilPsicologoDetail>>,
          TError,
          Awaited<ReturnType<typeof perfilPsicologoDetail>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function usePerfilPsicologoDetail<
  TData = Awaited<ReturnType<typeof perfilPsicologoDetail>>,
  TError = ErrorType<null | null>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof perfilPsicologoDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof perfilPsicologoDetail>>,
          TError,
          Awaited<ReturnType<typeof perfilPsicologoDetail>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function usePerfilPsicologoDetail<
  TData = Awaited<ReturnType<typeof perfilPsicologoDetail>>,
  TError = ErrorType<null | null>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof perfilPsicologoDetail>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Retorna o perfil profissional do psicólogo autenticado
 */

export function usePerfilPsicologoDetail<
  TData = Awaited<ReturnType<typeof perfilPsicologoDetail>>,
  TError = ErrorType<null | null>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof perfilPsicologoDetail>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getPerfilPsicologoDetailQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * @summary Atualiza o perfil profissional do psicólogo autenticado
 */
export const perfilPsicologoUpdate = (
  patchedPerfilPsicologo: BodyType<NonReadonly<PatchedPerfilPsicologo>>,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<PerfilPsicologo>(
    {
      url: `/api/me/perfil/editar/`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: patchedPerfilPsicologo,
    },
    options
  )
}

export const getPerfilPsicologoUpdateMutationOptions = <
  TError = ErrorType<null | null | null>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof perfilPsicologoUpdate>>,
    TError,
    { data: BodyType<NonReadonly<PatchedPerfilPsicologo>> },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof perfilPsicologoUpdate>>,
  TError,
  { data: BodyType<NonReadonly<PatchedPerfilPsicologo>> },
  TContext
> => {
  const mutationKey = ['perfilPsicologoUpdate']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof perfilPsicologoUpdate>>,
    { data: BodyType<NonReadonly<PatchedPerfilPsicologo>> }
  > = props => {
    const { data } = props ?? {}

    return perfilPsicologoUpdate(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PerfilPsicologoUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof perfilPsicologoUpdate>>
>
export type PerfilPsicologoUpdateMutationBody = BodyType<
  NonReadonly<PatchedPerfilPsicologo>
>
export type PerfilPsicologoUpdateMutationError = ErrorType<null | null | null>

/**
 * @summary Atualiza o perfil profissional do psicólogo autenticado
 */
export const usePerfilPsicologoUpdate = <
  TError = ErrorType<null | null | null>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof perfilPsicologoUpdate>>,
      TError,
      { data: BodyType<NonReadonly<PatchedPerfilPsicologo>> },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof perfilPsicologoUpdate>>,
  TError,
  { data: BodyType<NonReadonly<PatchedPerfilPsicologo>> },
  TContext
> => {
  const mutationOptions = getPerfilPsicologoUpdateMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Recebe um objeto JSON e cria um usuário do tipo `PSICÓLOGO`, associando-o à instituição do gestor autenticado. O usuário deve possuir as permissões adequadas (`GESTOR`) para realizar esta ação.
 * @summary Cadastra um psicólogo
 */
export const cadastrarPsicologo = (
  cadastrarPsicologo: BodyType<CadastrarPsicologo>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<CadastrarPsicologo>(
    {
      url: `/api/psicologos/`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: cadastrarPsicologo,
      signal,
    },
    options
  )
}

export const getCadastrarPsicologoMutationOptions = <
  TError = ErrorType<null | null>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof cadastrarPsicologo>>,
    TError,
    { data: BodyType<CadastrarPsicologo> },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof cadastrarPsicologo>>,
  TError,
  { data: BodyType<CadastrarPsicologo> },
  TContext
> => {
  const mutationKey = ['cadastrarPsicologo']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof cadastrarPsicologo>>,
    { data: BodyType<CadastrarPsicologo> }
  > = props => {
    const { data } = props ?? {}

    return cadastrarPsicologo(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type CadastrarPsicologoMutationResult = NonNullable<
  Awaited<ReturnType<typeof cadastrarPsicologo>>
>
export type CadastrarPsicologoMutationBody = BodyType<CadastrarPsicologo>
export type CadastrarPsicologoMutationError = ErrorType<null | null>

/**
 * @summary Cadastra um psicólogo
 */
export const useCadastrarPsicologo = <
  TError = ErrorType<null | null>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof cadastrarPsicologo>>,
      TError,
      { data: BodyType<CadastrarPsicologo> },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof cadastrarPsicologo>>,
  TError,
  { data: BodyType<CadastrarPsicologo> },
  TContext
> => {
  const mutationOptions = getCadastrarPsicologoMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Recebe um objeto JSON e cria um usuário com base nos dados enviados, podendo ser ou do tipo `PSICÓLOGO` ou `GESTOR`.
 * @summary Cria um usuário
 */
export const usuarioCreate = (
  customRegister: BodyType<CustomRegister>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<CustomRegister>(
    {
      url: `/api/usuarios/`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: customRegister,
      signal,
    },
    options
  )
}

export const getUsuarioCreateMutationOptions = <
  TError = ErrorType<null>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usuarioCreate>>,
    TError,
    { data: BodyType<CustomRegister> },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof usuarioCreate>>,
  TError,
  { data: BodyType<CustomRegister> },
  TContext
> => {
  const mutationKey = ['usuarioCreate']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof usuarioCreate>>,
    { data: BodyType<CustomRegister> }
  > = props => {
    const { data } = props ?? {}

    return usuarioCreate(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UsuarioCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof usuarioCreate>>
>
export type UsuarioCreateMutationBody = BodyType<CustomRegister>
export type UsuarioCreateMutationError = ErrorType<null>

/**
 * @summary Cria um usuário
 */
export const useUsuarioCreate = <TError = ErrorType<null>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof usuarioCreate>>,
      TError,
      { data: BodyType<CustomRegister> },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof usuarioCreate>>,
  TError,
  { data: BodyType<CustomRegister> },
  TContext
> => {
  const mutationOptions = getUsuarioCreateMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
