/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type {
  CustomRegister,
  Instituicao,
  MUser,
  PatchedInstituicao,
  PerfilPsicologo,
} from '../../models'

import { customInstance } from '../../mutator/custom-instance'
import type { ErrorType, BodyType } from '../../mutator/custom-instance'

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
  T,
>() => T extends Y ? 1 : 2
  ? A
  : B

type WritableKeys<T> = {
  [P in keyof T]-?: IfEquals<
    { [Q in P]: T[P] },
    { -readonly [Q in P]: T[P] },
    P
  >
}[keyof T]

type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (
  k: infer I
) => void
  ? I
  : never
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never

type Writable<T> = Pick<T, WritableKeys<T>>
type NonReadonly<T> = [T] extends [UnionToIntersection<T>]
  ? {
      [P in keyof Writable<T>]: T[P] extends object
        ? NonReadonly<NonNullable<T[P]>>
        : T[P]
    }
  : DistributeReadOnlyOverUnions<T>

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Atualiza os detalhes da instituição em que o usuário da requisição é gestor
 * @summary Atualiza os dados de uma instituição
 */
export const instituicaoUpdate = (
  patchedInstituicao: BodyType<NonReadonly<PatchedInstituicao>>,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<Instituicao>(
    {
      url: `/api/instituicoes/editar/`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: patchedInstituicao,
    },
    options
  )
}

export const getInstituicaoUpdateMutationOptions = <
  TError = ErrorType<null | null>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof instituicaoUpdate>>,
    TError,
    { data: BodyType<NonReadonly<PatchedInstituicao>> },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof instituicaoUpdate>>,
  TError,
  { data: BodyType<NonReadonly<PatchedInstituicao>> },
  TContext
> => {
  const mutationKey = ['instituicaoUpdate']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof instituicaoUpdate>>,
    { data: BodyType<NonReadonly<PatchedInstituicao>> }
  > = props => {
    const { data } = props ?? {}

    return instituicaoUpdate(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type InstituicaoUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof instituicaoUpdate>>
>
export type InstituicaoUpdateMutationBody = BodyType<
  NonReadonly<PatchedInstituicao>
>
export type InstituicaoUpdateMutationError = ErrorType<null | null>

/**
 * @summary Atualiza os dados de uma instituição
 */
export const useInstituicaoUpdate = <
  TError = ErrorType<null | null>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof instituicaoUpdate>>,
      TError,
      { data: BodyType<NonReadonly<PatchedInstituicao>> },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof instituicaoUpdate>>,
  TError,
  { data: BodyType<NonReadonly<PatchedInstituicao>> },
  TContext
> => {
  const mutationOptions = getInstituicaoUpdateMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Retorna uma lista com todos os psicólogos vinculados à instituição do gestor autenticado. Inclui tanto supervisores quanto estagiários.
 * @summary Listar psicólogos da instituição do gestor
 */
export const listarPsicologosInstituicao = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<PerfilPsicologo[]>(
    { url: `/api/instituicoes/psicologos/`, method: 'GET', signal },
    options
  )
}

export const getListarPsicologosInstituicaoQueryKey = () => {
  return [`/api/instituicoes/psicologos/`] as const
}

export const getListarPsicologosInstituicaoQueryOptions = <
  TData = Awaited<ReturnType<typeof listarPsicologosInstituicao>>,
  TError = ErrorType<null | null>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof listarPsicologosInstituicao>>,
      TError,
      TData
    >
  >
  request?: SecondParameter<typeof customInstance>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getListarPsicologosInstituicaoQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listarPsicologosInstituicao>>
  > = ({ signal }) => listarPsicologosInstituicao(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listarPsicologosInstituicao>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListarPsicologosInstituicaoQueryResult = NonNullable<
  Awaited<ReturnType<typeof listarPsicologosInstituicao>>
>
export type ListarPsicologosInstituicaoQueryError = ErrorType<null | null>

export function useListarPsicologosInstituicao<
  TData = Awaited<ReturnType<typeof listarPsicologosInstituicao>>,
  TError = ErrorType<null | null>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listarPsicologosInstituicao>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listarPsicologosInstituicao>>,
          TError,
          Awaited<ReturnType<typeof listarPsicologosInstituicao>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useListarPsicologosInstituicao<
  TData = Awaited<ReturnType<typeof listarPsicologosInstituicao>>,
  TError = ErrorType<null | null>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listarPsicologosInstituicao>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listarPsicologosInstituicao>>,
          TError,
          Awaited<ReturnType<typeof listarPsicologosInstituicao>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useListarPsicologosInstituicao<
  TData = Awaited<ReturnType<typeof listarPsicologosInstituicao>>,
  TError = ErrorType<null | null>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listarPsicologosInstituicao>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Listar psicólogos da instituição do gestor
 */

export function useListarPsicologosInstituicao<
  TData = Awaited<ReturnType<typeof listarPsicologosInstituicao>>,
  TError = ErrorType<null | null>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listarPsicologosInstituicao>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getListarPsicologosInstituicaoQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Lista todos os detalhes da instituição em que o usuário da requisição é gestor
 * @summary Lista os detalhes de uma instituição
 */
export const instituicaoDetail = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<Instituicao>(
    { url: `/api/instituicoes/ver/`, method: 'GET', signal },
    options
  )
}

export const getInstituicaoDetailQueryKey = () => {
  return [`/api/instituicoes/ver/`] as const
}

export const getInstituicaoDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof instituicaoDetail>>,
  TError = ErrorType<null | null>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof instituicaoDetail>>,
      TError,
      TData
    >
  >
  request?: SecondParameter<typeof customInstance>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getInstituicaoDetailQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof instituicaoDetail>>
  > = ({ signal }) => instituicaoDetail(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof instituicaoDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type InstituicaoDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof instituicaoDetail>>
>
export type InstituicaoDetailQueryError = ErrorType<null | null>

export function useInstituicaoDetail<
  TData = Awaited<ReturnType<typeof instituicaoDetail>>,
  TError = ErrorType<null | null>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof instituicaoDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof instituicaoDetail>>,
          TError,
          Awaited<ReturnType<typeof instituicaoDetail>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useInstituicaoDetail<
  TData = Awaited<ReturnType<typeof instituicaoDetail>>,
  TError = ErrorType<null | null>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof instituicaoDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof instituicaoDetail>>,
          TError,
          Awaited<ReturnType<typeof instituicaoDetail>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useInstituicaoDetail<
  TData = Awaited<ReturnType<typeof instituicaoDetail>>,
  TError = ErrorType<null | null>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof instituicaoDetail>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Lista os detalhes de uma instituição
 */

export function useInstituicaoDetail<
  TData = Awaited<ReturnType<typeof instituicaoDetail>>,
  TError = ErrorType<null | null>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof instituicaoDetail>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getInstituicaoDetailQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Retorna todas as informações referentes ao usuário que fez a requisição
 * @summary Retorna os dados do usuário da requisição
 */
export const profileView = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<MUser>(
    { url: `/api/me/profile/`, method: 'GET', signal },
    options
  )
}

export const getProfileViewQueryKey = () => {
  return [`/api/me/profile/`] as const
}

export const getProfileViewQueryOptions = <
  TData = Awaited<ReturnType<typeof profileView>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof profileView>>, TError, TData>
  >
  request?: SecondParameter<typeof customInstance>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getProfileViewQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof profileView>>> = ({
    signal,
  }) => profileView(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof profileView>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ProfileViewQueryResult = NonNullable<
  Awaited<ReturnType<typeof profileView>>
>
export type ProfileViewQueryError = ErrorType<unknown>

export function useProfileView<
  TData = Awaited<ReturnType<typeof profileView>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof profileView>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof profileView>>,
          TError,
          Awaited<ReturnType<typeof profileView>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useProfileView<
  TData = Awaited<ReturnType<typeof profileView>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof profileView>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof profileView>>,
          TError,
          Awaited<ReturnType<typeof profileView>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useProfileView<
  TData = Awaited<ReturnType<typeof profileView>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof profileView>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Retorna os dados do usuário da requisição
 */

export function useProfileView<
  TData = Awaited<ReturnType<typeof profileView>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof profileView>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getProfileViewQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Usa os dados de id e token (gerados automaticamente) para autenticar e aprovar um usuário como estagiário
 * @summary Aprova um estagiário
 */
export const aprovarEstagiario = (
  id: string,
  token: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<null>(
    { url: `/api/users/aprovar/${id}/${token}/`, method: 'GET', signal },
    options
  )
}

export const getAprovarEstagiarioQueryKey = (id?: string, token?: string) => {
  return [`/api/users/aprovar/${id}/${token}/`] as const
}

export const getAprovarEstagiarioQueryOptions = <
  TData = Awaited<ReturnType<typeof aprovarEstagiario>>,
  TError = ErrorType<null | null>,
>(
  id: string,
  token: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof aprovarEstagiario>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getAprovarEstagiarioQueryKey(id, token)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof aprovarEstagiario>>
  > = ({ signal }) => aprovarEstagiario(id, token, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: !!(id && token),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof aprovarEstagiario>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AprovarEstagiarioQueryResult = NonNullable<
  Awaited<ReturnType<typeof aprovarEstagiario>>
>
export type AprovarEstagiarioQueryError = ErrorType<null | null>

export function useAprovarEstagiario<
  TData = Awaited<ReturnType<typeof aprovarEstagiario>>,
  TError = ErrorType<null | null>,
>(
  id: string,
  token: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof aprovarEstagiario>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof aprovarEstagiario>>,
          TError,
          Awaited<ReturnType<typeof aprovarEstagiario>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useAprovarEstagiario<
  TData = Awaited<ReturnType<typeof aprovarEstagiario>>,
  TError = ErrorType<null | null>,
>(
  id: string,
  token: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof aprovarEstagiario>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof aprovarEstagiario>>,
          TError,
          Awaited<ReturnType<typeof aprovarEstagiario>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useAprovarEstagiario<
  TData = Awaited<ReturnType<typeof aprovarEstagiario>>,
  TError = ErrorType<null | null>,
>(
  id: string,
  token: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof aprovarEstagiario>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Aprova um estagiário
 */

export function useAprovarEstagiario<
  TData = Awaited<ReturnType<typeof aprovarEstagiario>>,
  TError = ErrorType<null | null>,
>(
  id: string,
  token: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof aprovarEstagiario>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getAprovarEstagiarioQueryOptions(id, token, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Recebe um objeto JSON e cria um usuário com base nos dados enviados, podendo ser ou do tipo `PSICÓLOGO` ou `GESTOR`.
 * @summary Cria um usuário
 */
export const psicologoCreate = (
  customRegister: BodyType<CustomRegister>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<CustomRegister>(
    {
      url: `/api/users/cadastrar/`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: customRegister,
      signal,
    },
    options
  )
}

export const getPsicologoCreateMutationOptions = <
  TError = ErrorType<null>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof psicologoCreate>>,
    TError,
    { data: BodyType<CustomRegister> },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof psicologoCreate>>,
  TError,
  { data: BodyType<CustomRegister> },
  TContext
> => {
  const mutationKey = ['psicologoCreate']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof psicologoCreate>>,
    { data: BodyType<CustomRegister> }
  > = props => {
    const { data } = props ?? {}

    return psicologoCreate(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PsicologoCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof psicologoCreate>>
>
export type PsicologoCreateMutationBody = BodyType<CustomRegister>
export type PsicologoCreateMutationError = ErrorType<null>

/**
 * @summary Cria um usuário
 */
export const usePsicologoCreate = <
  TError = ErrorType<null>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof psicologoCreate>>,
      TError,
      { data: BodyType<CustomRegister> },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof psicologoCreate>>,
  TError,
  { data: BodyType<CustomRegister> },
  TContext
> => {
  const mutationOptions = getPsicologoCreateMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Permite que um **gestor** remova o supervisor atualmente associado a um estagiário da sua instituição. Após a remoção, o campo `supervisor_confirmado` é definido como `False`.
 * @summary Remover supervisor de um estagiário
 */
export const apiUsersRemoverSupervisorPartialUpdate = (
  estagiario: string,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<null>(
    { url: `/api/users/remover-supervisor/${estagiario}/`, method: 'PATCH' },
    options
  )
}

export const getApiUsersRemoverSupervisorPartialUpdateMutationOptions = <
  TError = ErrorType<null | null | null>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiUsersRemoverSupervisorPartialUpdate>>,
    TError,
    { estagiario: string },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof apiUsersRemoverSupervisorPartialUpdate>>,
  TError,
  { estagiario: string },
  TContext
> => {
  const mutationKey = ['apiUsersRemoverSupervisorPartialUpdate']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiUsersRemoverSupervisorPartialUpdate>>,
    { estagiario: string }
  > = props => {
    const { estagiario } = props ?? {}

    return apiUsersRemoverSupervisorPartialUpdate(estagiario, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ApiUsersRemoverSupervisorPartialUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof apiUsersRemoverSupervisorPartialUpdate>>
>

export type ApiUsersRemoverSupervisorPartialUpdateMutationError = ErrorType<
  null | null | null
>

/**
 * @summary Remover supervisor de um estagiário
 */
export const useApiUsersRemoverSupervisorPartialUpdate = <
  TError = ErrorType<null | null | null>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof apiUsersRemoverSupervisorPartialUpdate>>,
      TError,
      { estagiario: string },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof apiUsersRemoverSupervisorPartialUpdate>>,
  TError,
  { estagiario: string },
  TContext
> => {
  const mutationOptions =
    getApiUsersRemoverSupervisorPartialUpdateMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Permite que um **gestor** troque o supervisor associado a um estagiário dentro da mesma instituição. Apenas gestores da instituição do estagiário e do novo supervisor podem executar esta operação.
 * @summary Trocar supervisor de um estagiário
 */
export const apiUsersTrocarSupervisorPartialUpdate = (
  estagiario: string,
  novoSupervisor: string,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<null>(
    {
      url: `/api/users/trocar-supervisor/${estagiario}/${novoSupervisor}/`,
      method: 'PATCH',
    },
    options
  )
}

export const getApiUsersTrocarSupervisorPartialUpdateMutationOptions = <
  TError = ErrorType<null | null | null>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiUsersTrocarSupervisorPartialUpdate>>,
    TError,
    { estagiario: string; novoSupervisor: string },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof apiUsersTrocarSupervisorPartialUpdate>>,
  TError,
  { estagiario: string; novoSupervisor: string },
  TContext
> => {
  const mutationKey = ['apiUsersTrocarSupervisorPartialUpdate']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiUsersTrocarSupervisorPartialUpdate>>,
    { estagiario: string; novoSupervisor: string }
  > = props => {
    const { estagiario, novoSupervisor } = props ?? {}

    return apiUsersTrocarSupervisorPartialUpdate(
      estagiario,
      novoSupervisor,
      requestOptions
    )
  }

  return { mutationFn, ...mutationOptions }
}

export type ApiUsersTrocarSupervisorPartialUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof apiUsersTrocarSupervisorPartialUpdate>>
>

export type ApiUsersTrocarSupervisorPartialUpdateMutationError = ErrorType<
  null | null | null
>

/**
 * @summary Trocar supervisor de um estagiário
 */
export const useApiUsersTrocarSupervisorPartialUpdate = <
  TError = ErrorType<null | null | null>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof apiUsersTrocarSupervisorPartialUpdate>>,
      TError,
      { estagiario: string; novoSupervisor: string },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof apiUsersTrocarSupervisorPartialUpdate>>,
  TError,
  { estagiario: string; novoSupervisor: string },
  TContext
> => {
  const mutationOptions =
    getApiUsersTrocarSupervisorPartialUpdateMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
