/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * MindMeet API
 * API REST do **MindMeet**, uma plataforma de gestão para clínicas e consultórios de psicologia.

Permite o gerenciamento completo de psicólogos, pacientes, agendamentos e anotações clínicas, com suporte a dois modelos de operação:

- **Independente** — psicólogo autônomo que gerencia sua própria agenda e pacientes.
- **Institucional** — psicólogos e estagiários vinculados a uma instituição, supervisionados por um gestor.

A autenticação é feita via **JWT**. Todos os endpoints protegidos exigem o token no header `Authorization: Bearer <token>`.
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type {
  PacienteDetail,
  PacienteListParams,
  PaginatedPacienteListList,
  PatchedPacienteDetail,
} from '../../models'

import { customInstance } from '../../mutator/custom-instance'
import type { ErrorType, BodyType } from '../../mutator/custom-instance'

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
  T,
>() => T extends Y ? 1 : 2
  ? A
  : B

type WritableKeys<T> = {
  [P in keyof T]-?: IfEquals<
    { [Q in P]: T[P] },
    { -readonly [Q in P]: T[P] },
    P
  >
}[keyof T]

type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (
  k: infer I
) => void
  ? I
  : never
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never

type Writable<T> = Pick<T, WritableKeys<T>>
type NonReadonly<T> = [T] extends [UnionToIntersection<T>]
  ? {
      [P in keyof Writable<T>]: T[P] extends object
        ? NonReadonly<NonNullable<T[P]>>
        : T[P]
    }
  : DistributeReadOnlyOverUnions<T>

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Retorna uma lista com todos os pacientes associados a um psicólogo ou à instituição do gestor que fez a requisição
 * @summary Lista todos os pacientes
 */
export const pacienteList = (
  params?: PacienteListParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<PaginatedPacienteListList>(
    { url: `/api/pacientes/`, method: 'GET', params, signal },
    options
  )
}

export const getPacienteListQueryKey = (params?: PacienteListParams) => {
  return [`/api/pacientes/`, ...(params ? [params] : [])] as const
}

export const getPacienteListQueryOptions = <
  TData = Awaited<ReturnType<typeof pacienteList>>,
  TError = ErrorType<null | null>,
>(
  params?: PacienteListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof pacienteList>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getPacienteListQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof pacienteList>>> = ({
    signal,
  }) => pacienteList(params, requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof pacienteList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PacienteListQueryResult = NonNullable<
  Awaited<ReturnType<typeof pacienteList>>
>
export type PacienteListQueryError = ErrorType<null | null>

export function usePacienteList<
  TData = Awaited<ReturnType<typeof pacienteList>>,
  TError = ErrorType<null | null>,
>(
  params: undefined | PacienteListParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof pacienteList>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof pacienteList>>,
          TError,
          Awaited<ReturnType<typeof pacienteList>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function usePacienteList<
  TData = Awaited<ReturnType<typeof pacienteList>>,
  TError = ErrorType<null | null>,
>(
  params?: PacienteListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof pacienteList>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof pacienteList>>,
          TError,
          Awaited<ReturnType<typeof pacienteList>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function usePacienteList<
  TData = Awaited<ReturnType<typeof pacienteList>>,
  TError = ErrorType<null | null>,
>(
  params?: PacienteListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof pacienteList>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Lista todos os pacientes
 */

export function usePacienteList<
  TData = Awaited<ReturnType<typeof pacienteList>>,
  TError = ErrorType<null | null>,
>(
  params?: PacienteListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof pacienteList>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getPacienteListQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Recebe um objeto JSON e cria um paciente vinculado ao psicólogo ou instituição do gestor que fez requisição.
 * @summary Cria um novo paciente
 */
export const pacienteCreate = (
  pacienteDetail: BodyType<NonReadonly<PacienteDetail>>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<PacienteDetail>(
    {
      url: `/api/pacientes/`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: pacienteDetail,
      signal,
    },
    options
  )
}

export const getPacienteCreateMutationOptions = <
  TError = ErrorType<null | null>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof pacienteCreate>>,
    TError,
    { data: BodyType<NonReadonly<PacienteDetail>> },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof pacienteCreate>>,
  TError,
  { data: BodyType<NonReadonly<PacienteDetail>> },
  TContext
> => {
  const mutationKey = ['pacienteCreate']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof pacienteCreate>>,
    { data: BodyType<NonReadonly<PacienteDetail>> }
  > = props => {
    const { data } = props ?? {}

    return pacienteCreate(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PacienteCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof pacienteCreate>>
>
export type PacienteCreateMutationBody = BodyType<NonReadonly<PacienteDetail>>
export type PacienteCreateMutationError = ErrorType<null | null>

/**
 * @summary Cria um novo paciente
 */
export const usePacienteCreate = <
  TError = ErrorType<null | null>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof pacienteCreate>>,
      TError,
      { data: BodyType<NonReadonly<PacienteDetail>> },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof pacienteCreate>>,
  TError,
  { data: BodyType<NonReadonly<PacienteDetail>> },
  TContext
> => {
  const mutationOptions = getPacienteCreateMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Retorna todos os dados referentes a um paciente. Também vísivel ao supervisor do psicólogo.
 * @summary Obtém detalhes sobre um paciente
 */
export const pacienteDetail = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<PacienteDetail>(
    { url: `/api/pacientes/${id}/`, method: 'GET', signal },
    options
  )
}

export const getPacienteDetailQueryKey = (id?: string) => {
  return [`/api/pacientes/${id}/`] as const
}

export const getPacienteDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof pacienteDetail>>,
  TError = ErrorType<null | null | null>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof pacienteDetail>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getPacienteDetailQueryKey(id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof pacienteDetail>>> = ({
    signal,
  }) => pacienteDetail(id, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof pacienteDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PacienteDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof pacienteDetail>>
>
export type PacienteDetailQueryError = ErrorType<null | null | null>

export function usePacienteDetail<
  TData = Awaited<ReturnType<typeof pacienteDetail>>,
  TError = ErrorType<null | null | null>,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof pacienteDetail>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof pacienteDetail>>,
          TError,
          Awaited<ReturnType<typeof pacienteDetail>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function usePacienteDetail<
  TData = Awaited<ReturnType<typeof pacienteDetail>>,
  TError = ErrorType<null | null | null>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof pacienteDetail>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof pacienteDetail>>,
          TError,
          Awaited<ReturnType<typeof pacienteDetail>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function usePacienteDetail<
  TData = Awaited<ReturnType<typeof pacienteDetail>>,
  TError = ErrorType<null | null | null>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof pacienteDetail>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Obtém detalhes sobre um paciente
 */

export function usePacienteDetail<
  TData = Awaited<ReturnType<typeof pacienteDetail>>,
  TError = ErrorType<null | null | null>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof pacienteDetail>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getPacienteDetailQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Recebe um objeto JSON e atualiza ou cria os campos de um paciente.
 * @summary Atualiza os dados de um paciente
 */
export const pacienteUpdate = (
  id: string,
  patchedPacienteDetail: BodyType<NonReadonly<PatchedPacienteDetail>>,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<PacienteDetail>(
    {
      url: `/api/pacientes/${id}/`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: patchedPacienteDetail,
    },
    options
  )
}

export const getPacienteUpdateMutationOptions = <
  TError = ErrorType<null | null | null>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof pacienteUpdate>>,
    TError,
    { id: string; data: BodyType<NonReadonly<PatchedPacienteDetail>> },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof pacienteUpdate>>,
  TError,
  { id: string; data: BodyType<NonReadonly<PatchedPacienteDetail>> },
  TContext
> => {
  const mutationKey = ['pacienteUpdate']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof pacienteUpdate>>,
    { id: string; data: BodyType<NonReadonly<PatchedPacienteDetail>> }
  > = props => {
    const { id, data } = props ?? {}

    return pacienteUpdate(id, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PacienteUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof pacienteUpdate>>
>
export type PacienteUpdateMutationBody = BodyType<
  NonReadonly<PatchedPacienteDetail>
>
export type PacienteUpdateMutationError = ErrorType<null | null | null>

/**
 * @summary Atualiza os dados de um paciente
 */
export const usePacienteUpdate = <
  TError = ErrorType<null | null | null>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof pacienteUpdate>>,
      TError,
      { id: string; data: BodyType<NonReadonly<PatchedPacienteDetail>> },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof pacienteUpdate>>,
  TError,
  { id: string; data: BodyType<NonReadonly<PatchedPacienteDetail>> },
  TContext
> => {
  const mutationOptions = getPacienteUpdateMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Apaga todos os dados e objetos atrelados a um paciente
 * @summary Apaga um paciente
 */
export const pacienteDelete = (
  id: string,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<null>(
    { url: `/api/pacientes/${id}/`, method: 'DELETE' },
    options
  )
}

export const getPacienteDeleteMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof pacienteDelete>>,
    TError,
    { id: string },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof pacienteDelete>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['pacienteDelete']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof pacienteDelete>>,
    { id: string }
  > = props => {
    const { id } = props ?? {}

    return pacienteDelete(id, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PacienteDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof pacienteDelete>>
>

export type PacienteDeleteMutationError = ErrorType<unknown>

/**
 * @summary Apaga um paciente
 */
export const usePacienteDelete = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof pacienteDelete>>,
      TError,
      { id: string },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof pacienteDelete>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getPacienteDeleteMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Permite que um **gestor** troque o psicólogo associado a um paciente dentro da mesma instituição. Apenas gestores da instituição do paciente e do novo psicólogo podem executar esta operação.
 * @summary Troca o psicólogo de um paciente.
 */
export const trocarPsicologo = (
  id: string,
  novoPsicologo: string,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<null>(
    {
      url: `/api/pacientes/${id}/trocar-psicologo/${novoPsicologo}/`,
      method: 'PATCH',
    },
    options
  )
}

export const getTrocarPsicologoMutationOptions = <
  TError = ErrorType<null | null | null>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof trocarPsicologo>>,
    TError,
    { id: string; novoPsicologo: string },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof trocarPsicologo>>,
  TError,
  { id: string; novoPsicologo: string },
  TContext
> => {
  const mutationKey = ['trocarPsicologo']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof trocarPsicologo>>,
    { id: string; novoPsicologo: string }
  > = props => {
    const { id, novoPsicologo } = props ?? {}

    return trocarPsicologo(id, novoPsicologo, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type TrocarPsicologoMutationResult = NonNullable<
  Awaited<ReturnType<typeof trocarPsicologo>>
>

export type TrocarPsicologoMutationError = ErrorType<null | null | null>

/**
 * @summary Troca o psicólogo de um paciente.
 */
export const useTrocarPsicologo = <
  TError = ErrorType<null | null | null>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof trocarPsicologo>>,
      TError,
      { id: string; novoPsicologo: string },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof trocarPsicologo>>,
  TError,
  { id: string; novoPsicologo: string },
  TContext
> => {
  const mutationOptions = getTrocarPsicologoMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
